### ISSUE TITLE
Fixed path: C:/building/ in VTK cmake files, after update using pacman -Su 

### ISSUE THREAD

**Issue by tiedtke** [Alexpux/MINGW-packages#1024]
After a update using pacman -Su, new version of VTK and HDF5 libs were installed, and some fixed path were write in .cmake files.

It's not a big problem, but after all update these path:

C:/building/msys64/mingw64/lib/

are added again in every .cmake file of VTK/HDF5 libs, needing some manual editing, due my system are installed in:

C:/msys64/msys64/mingw64/lib/

**Comment by Mikayex** [comment]
I have the same issue.
Actually the fix is already in the PKGBUILD but it is commented for whatever reason. Removing the comments line [131](https://github.com/Alexpux/MINGW-packages/blob/51b744768548af632620efb2b50a768809d8eb90/mingw-w64-vtk/PKGBUILD#L136), [136-137](https://github.com/Alexpux/MINGW-packages/blob/51b744768548af632620efb2b50a768809d8eb90/mingw-w64-vtk/PKGBUILD#L136-L137) fixes the issue.

**Comment by letmaik** [comment]
Looks like this is fixed for HDF5 now: https://github.com/Alexpux/MINGW-packages/commit/f202d24f75566367a5a6b467d8843997349fbee2#diff-f4dfb2524ae519995c350f7b4f923707
