### ISSUE TITLE
Please, update webkitgtk

### ISSUE THREAD

**Issue by tpimh** [Alexpux/MINGW-packages#1089]
[This package](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-webkitgtk3) is dramatically outdated. For now actual versions are 2.10.7 (stable) and 2.11.90 (unstable).

Are there any reasons why it was not updated?

And why WebKit 2 API is disabled during configure? It should now compile and be fine.

**Comment by Alexpux** [comment]
Webkit2 not buildable with mingw. Webkitgtk 2.4.x is the latest that building with mingw

**Comment by tpimh** [comment]
Quoting #webkitgtk+ IRC channel:
    [21:22] <pfor> there were some patches for older checkout on github for wk2
    [21:22] <pfor> everything was stubbed out but it was building at least
    [21:23] <pfor> but as far as i know it was not touched since

**Comment by Alexpux** [comment]
Ok, maybe you then submit patches and changes to us? But before test build yourself. Don't push half-working solution

**Comment by tpimh** [comment]
Here is the [link](https://github.com/epienbroek/webkit/tree/mingw_wip) to the repo.

I will try to build it. If I can get it working, this will also allow other applications that depend on it to be built.

**Comment by mingwandroid** [comment]
Stubbed-out means not implemented, but if you wish to write all those missing functions and files you will truly win all the internets.

Good luck my friend.

**Comment by tpimh** [comment]
Hmm, looks like a lot of work. I would rather use CEF instead.

**Comment by mingwandroid** [comment]
Great, so you are going to port Chromium to MinGW-w64 instead? Fantastic!

**Comment by mingwandroid** [comment]
You will need to port MS's __try() __except() stuff to GCC for Google's Sandbox framework, here is a link to get started:

https://msdn.microsoft.com/en-us/library/swezty51.aspx

**Comment by DavidEGrayson** [comment]
I don't know how usable clang is on MSYS2, but a way forward might be to use clang to compile code that requires `__try` and `__except`.  They have a page documenting their efforts to be compatible with MSVC:

http://clang.llvm.org/docs/MSVCCompatibility.html

**Comment by mingwandroid** [comment]
I'd say it needs some work, but it's definitely an interesting approach.

**Comment by DavidEGrayson** [comment]
Well, if clang uses the MSVC C++ ABI then the stuff compiled with clang won't be compatible with any of our other C++ libraries, so that could be a pain.

It might be possible to just add SEH to GCC.  This page talks about SEH in GCC and says that "Casper Hornstrup had created an initial implementation, but it was never merged into mainline GCC."

https://gcc.gnu.org/wiki/WindowsGCCImprovements

Also it looks like someone worked on this is a Summer of Code project in 2007:

https://gcc.gnu.org/wiki/SummerOfCode

I'm considering spending some of my time to look into this and make a SEH patch for GCC 5.3.0, though I don't know much about GCC and this could take a while.

**Comment by lazka** [comment]
Closing in favor of #3484, which has some new information (but no real progress, so don't get your hopes up)
