### ISSUE TITLE
mingw-w64-i686-gc-7.4.2-2 & mingw-w64-x86_64-gc-7.4.2-2 hang

### ISSUE THREAD

**Issue by Beluki** [Alexpux/MINGW-packages#1110]
I've been trying to use libgc to build a scheme interpreter and it seems to be broken on both MINGW32 and MINGW64. It randomly hangs the program.

Here's an example program that reproduces the issue:

``` c
#include <gc.h>
#include <stdio.h>

#define malloc GC_MALLOC

int main(int argc, char *argv[]) {
    puts("Hello");

    for (int i = 0; i < 100; i++)
    {
        printf("%d \n", i);
        malloc(1024 * 1024);
    }

    puts("World");
    return 0;
}
```

Compiled with `gcc gc-test.c -lgc` in my system:
- It always works with MSYS.
- It hangs on both MINGW32 and MINGW64 on different loop iterations or even before printing "hello". Multiple runs produce different results (like 1/10 of the times it does actually work).

I've tested more complex programs, including the full scheme interpreter, which does build and also hang only on MINGW32/MINGW64 when running any memory-intensive program.

Packages:
mingw-w64-x86_64-gc-7.4.2-2
mingw-w64-x86_64-libatomic_ops
mingw-w64-i686-gc-7.4.2-2
mingw-w64-i686-libatomic_ops

**Comment by DavidEGrayson** [comment]
Any compiled C or C++ program is suspect right now because of issue #1104.  Right now I am using these versions of the mingw-w64-x86_64-crt-git and mingw-w64-x86_64-headers-git packages: r4617.e0531bb, which should avoid issue #1104.

However even with a working crt-git pacakge, I am still able to reproduce your problem with gc.  It looks like the program hangs at a random point, although sometimes it does complete successfully.  Here is my slightly modified program which flushes stdout so we can see how far the program progresses:

~~~~{.c}
#include <gc.h>
#include <stdio.h>

#define malloc GC_MALLOC

int main(int argc, char *argv[]) {
    printf("Hello\n");
    fflush(stdout);

    for (int i = 0; i < 100; i++)
    {
        printf("%d\n", i);
        fflush(stdout);
        malloc(1024 * 1024);
    }

    printf("World\n");
    return 0;
}
~~~~

**Comment by DavidEGrayson** [comment]
When I compile a debug version of the mingw-w64-x86_64-gc package and single-step through the program in gdb using the "n" command repeatedly, the bug does not seem to happen.  So I'm thinking that this might be some kind of concurrency issue that depends on when threads are scheduled to run.

**Comment by DavidEGrayson** [comment]
Doesn't thread-local storage work fine in MinGW?  I see that the gc package is not configured to use the compiler TLS so it is using its own solution in this block of code in GC_malloc in thread_local_alloc.c:

~~~~{.c}
#   if !defined(USE_COMPILER_TLS) && !defined(USE_WIN32_COMPILER_TLS)
      if (EXPECT(0 == tsd, FALSE)) {
        GC_log_printf("GC_malloc(%lu) calling GC_core_malloc");
        return GC_core_malloc(bytes);
      }
#   endif
~~~~

**Comment by DavidEGrayson** [comment]
This library has a test suite that can be run with `make check`, and it also seems to hang indefinitely.

**Comment by DavidEGrayson** [comment]
@Beluki:  Try setting the environment variable GC_MARKERS to 1 when you run your program.

    GC_MARKERS=1 ./yourprogram.exe

It looks like that environment variable controls how many marking threads will be spawned.

**Comment by DavidEGrayson** [comment]
I figured out how to attach gdb to a running process and inspect its threads.  It's really neat that works!  It looks like a deadlock to me.  I see the main thread and the 4 marking threads (I specified `GC_MARKERS=4`) are all stuck in multi-threaded waiting functions.  Here are the stack traces: https://gist.github.com/DavidEGrayson/526f8e772343cf728a1d

The main thread is stuck in `GC_acquire_mark_lock`.  Thread 2 is stuck in `GC_wait_marker`.  Thread 3 is stuck in `GC_acquire_mark_lock`.   Thread 4 is stuck in `GC_notify_all_marker`.  Thread 5 is stuck in `GC_wait_marker`.  Thread 5 is actually special because the underlying native API function it is stuck in is ZwWaitForMultipleObjects, whereas all the other threads are in ZwWaitForSingleObject.

**Comment by Beluki** [comment]
Sorry I forgot to mention I was already using the downgraded packages after reading  issue #1104 yesterday:

mingw-w64-x86_64-crt-git-5.0.0.4609.566d621-1-any.pkg.tar.xz
mingw-w64-i686-crt-git-5.0.0.4609.566d621-1-any.pkg.tar.xz

@DavidEGrayson indeed, I can confirm that setting GC_MARKERS=1 fixes the issue on my system too. I've also tested the scheme interpreter and other complex programs and all seem to run without issues.

Thanks a lot for investigating!

**Comment by DavidEGrayson** [comment]
Cool.  Let's leave this issue open until the package  is fixed; setting GC_MARKERS is just a temporary workaround.
