### ISSUE TITLE
multiple pacman installed libraries have invalid cmake links

### ISSUE THREAD

**Issue by SimLeek** [Alexpux/MINGW-packages#1170]
when using msys to install packages with pacman, some of the cmake files in those packages (vtk and one other, ...glib? ...zlib?) including a non-existent directory called "building" before everything else when trying to link to other files. This means cmake can't compile these packages.

pacman: Pacman v4.2.1-503-g62b54-dirty - libalpm v10.0.1
vtk: mingw-w64-x86_64-vtk 6.3.0-2
gcc: mingw-w64-x86_64-gcc 5.3.0-2
cmake: mingw-w64-x86_64-cmake 3.4.1-1 ; mingw-w64-x86_64-extra-cmake-modules 5.18.0-1

**Comment by mingwandroid** [comment]
This is a general problem with cmake and the upstream packages to be honest with you. I fixed it for one package here:

https://github.com/Alexpux/MINGW-packages/commit/34ea54

.. this needs to be done for pretty much every CMake package, but I feel that the CMake project itself needs to figure this out.

**Comment by rpavlik** [comment]
It's an issue with the upstream package, typically when they include `${CMAKE_INSTALL_PREFIX}` in their `install(... DESTINATION` commands, but sometimes done much more subtly/insidiously than that. (There are many ways to misuse CMake, despite it being a very good build system...)  Typically, short of fixing every build system, something like this: https://github.com/Alexpux/MINGW-packages/pull/1346 is good enough for packaging purposes, since CMake does already create a "relative path" variable `${_INSTALL_PREFIX}` so there's no need to make our own AFAIK.

To be more resilient, we could extend that regex to check to ensure the `${MINGW_PREFIX}` is only replaced when used as the beginning of a path - check to see if it is preceded by `"`, semicolon (list delimiter), or whitespace or line beginning (would only show up in hand-generated parts of files there - CMake quotes the pieces it generates entirely on its own). (Furthermore, usually you would have a trailing slash, but some packages might use a "root directory" variable in which case you might have whitespace, double quote, or `)` following it...)   Might be getting a little out of range of sed there (or maybe just complicated sed capturing the possible thing before the prefix). In any case, if some common fixup were made, it would be nice to stick it in a package of its own so that it wouldn't be poorly-duplicated between PKGBUILDs.
