### ISSUE TITLE
bash broken : cannnot escape *

### ISSUE THREAD

**Issue by yumetodo** [Alexpux/MINGW-packages#1347]
[Ubuntu 16.04](https://twitter.com/173210/status/722598340869763073)
![on linux](https://pbs.twimg.com/media/CgctRt6UEAAXwbH.png)
msys2
![on msys2](https://pbs.twimg.com/media/CgculpOUAAEGl1A.jpg)

`gdb --args echo \*` is cleary broken.

However, `echo \*` work fine. What do you mean by???
# my env
- Windows7 64bit
- using mingw64_shell.bat
- pacman : 5.0.1.6403.520736d-1
- bash : 4.3.42(5)-release (x86_64-pc-msys)
- gdb 7.11

**Comment by yumetodo** [comment]
```
yumetodo@jpierreno-PC MSYS /c/Users/yumetodo/Documents/git/Shioi/I401
$ gdb --args echo \*
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from echo...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/echo \*
[New Thread 17916.0x4edc]
[New Thread 17916.0x505c]
[New Thread 17916.0x2a38]
[New Thread 17916.0x2d74]
*
[Thread 17916.0x2a38 exited with code 0]
[Thread 17916.0x2d74 exited with code 0]
[Inferior 1 (process 17916) exited normally]
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) quit


yumetodo@jpierreno-PC MSYS /c/Users/yumetodo/Documents/git/Shioi/I401
$ cat test.c
#include <stdio.h>
int main(int argc, char* argv[])
{
    int i;
    for(i = 0; i < argc; ++i){
        puts(argv[i]);
    }
    return 0;
}

yumetodo@jpierreno-PC MSYS /c/Users/yumetodo/Documents/git/Shioi/I401
$ gdb --args a.exe \*
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from a.exe...done.
(gdb) run
Starting program: /c/Users/yumetodo/Documents/git/Shioi/I401/a.exe \*
[New Thread 19756.0x478c]
C:\Users\yumetodo\Documents\git\Shioi\I401\a.exe
\$Recycle.Bin
\Documents and Settings
\for_cmd
\hiberfil.sys
\inetpub
\Intel
\lib
\mingw
\pagefile.sys
\PerfLogs
\Program Files
\Program Files (x86)
\program1
\ProgramData
\Python34
\Recovery
\System Volume Information
\Users
\Util
\Windows
\work
[Inferior 1 (process 19756) exited normally]
(gdb) quit
```

How shold I understand this behavior?

```
C:\>dir
 ドライブ C のボリューム ラベルがありません。
 ボリューム シリアル番号は D2D4-6602 です

 C:\ のディレクトリ

2016/04/12  01:52    <DIR>          for_cmd
2016/03/13  11:39    <DIR>          inetpub
2015/09/21  19:24    <DIR>          Intel
2016/02/13  22:58    <DIR>          lib
2015/09/13  19:22    <SYMLINKD>     mingw [D:\lsw-build2-master\msys64\mingw32]
2009/07/14  12:20    <DIR>          PerfLogs
2016/04/11  00:52    <DIR>          Program Files
2016/04/19  14:50    <DIR>          Program Files (x86)
2016/02/09  21:23    <DIR>          program1
2016/01/04  22:18    <DIR>          Python34
2016/03/13  11:41    <DIR>          Users
2016/04/08  11:44    <DIR>          Util
2016/04/20  00:09    <DIR>          Windows
2016/02/15  18:28    <DIR>          work
               0 個のファイル                   0 バイト
              14 個のディレクトリ  113,386,020,864 バイトの空き領域
```

**Comment by DavidEGrayson** [comment]
@yumetodo: I think this behavior is caused by the automatic, heuristic-based path conversions that msys-2.0.dll does whenever you try to run native Windows software (such as your 64-bit MinGW gdb) from an msys-2.0.dll-based program (such as bash).  There is more information about MSYS2 path conversions in the [Porting page on the wiki](https://sourceforge.net/p/msys2/wiki/Porting/).

I have reproduced the problem using a simpler setup that does not involve Bash or GDB.  You can see it in this [**interactive shell session demonstrating the problem**](https://gist.github.com/DavidEGrayson/ce75f97c9d9f68b74e20ee849a154e15).

What we can see is that when an msys-2.0.dll-based program (testexec.exe) runs another msys-2.0.dll-based program (msys2-echoargs.exe), there is no automatic path conversion in the arguments. But when msys-2.0.dll tries to run mingw-echoargs.exe, the argument `/c` gets converted to `C:/` and the argument `*` gets converted to a list of files in the current directory.  I don't understand why `*` would get converted, but `/c` generally needs to be converted because most native Windows programs would not understand a path like that.

In cases where the heuristics make a bad decision, you can *usually* use the `MSYS2_ARG_CONV_EXCL` environment variable to tell the msys-2.0.dll runtime that certain arguments should not be converted.  I think @mingwandroid explained that it is a list of prefixes or something like that, and any argument that matches one of those prefixes will not be converted.  If you set it to the empty string, then no arguments are supposed to get converted (the empty prefix matches all strings).  We can see from my shell session that setting `MSYS2_ARG_CONV_EXCL` to the empty string prevents the `/c` argument from being converted, but it has no effect on the `*` argument.  :confused:

This actually bit me just yesterday in a program I was working on.  My workaround was to add some other letters to the `*` argument, changing it into `*xyz`.  Since that pattern didn't match any files in the current directory, msys-2.0.dll did not convert it.

@AlexPux and @mingwandroid:  Any idea why arguments like `*` are still converted even if we set the `MSYS2_ARG_CONV_EXCL` environment variable to the empty string?  Does it make sense to convert `*` at all?

**Comment by mattn** [comment]
FYI, this doesn't occur on msys2 shell.

![](http://go-gyazo.appspot.com/586318ac1e0b0e17.png)

This occured on mingw64(maybe mingw32) shell.

![](http://go-gyazo.appspot.com/4b74495942918fc9.png)

**Comment by yumetodo** [comment]
So, mingw's routine around argument parser is broken(unpack ``*``), isn't it?

**Comment by mattn** [comment]
Yes, but as far as I can see, it's a bug of gdb.

**Comment by yumetodo** [comment]
@mattn 
where and how shold I post these bug? I've never post bug to mingw-project.

**Comment by mattn** [comment]
It's here maybe.

**Comment by DavidEGrayson** [comment]
For what it's worth, you can go into an empty directory using `cd` before running your command that has a `*` in it.  Then there will be no files that match the `*`, so the MSYS2 path converter will not expand it.

I still think this is a bug in the MSYS2 path conversion code.

**Comment by yumetodo** [comment]
>For what it's worth, you can go into an empty directory using cd before running your command that has a * in it. Then there will be no files that match the *, so the MSYS2 path converter will not expand it.

Oh...

>I still think this is a bug in the MSYS2 path conversion code.

```c
#include <stdio.h>
int main(int argc, char* argv[])
{
    for(int i = 1; i < argc; ++i) puts(argv[i]);
    return 0;
}
```

I compile this code by Visual Studio 2015 Update 2(static link) and run on mingw64_shell.bat

```sh
$ ./escape_test_msys2.exe \*
*
$ gdb --args escape_test_msys2.exe \*
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from escape_test_msys2.exe...(no debugging symbols found)...done.
(gdb) run
Starting program: D:\msys64\home\j.pierreno\escape_test_msys2.exe .bash_history .bash_logout .bash_profile .bashrc .gem .gitconfig .inputrc .minttyrc .profile buffers char_enc_test cybozu_1 escape_test_msys2.exe FFC▒Ńo▒b▒N▒A▒b▒v▒▒▒Ă݂▒+Vor103.bat opencv_test.cpp
[New Thread 8200.0x3d88]
.bash_history
.bash_logout
.bash_profile
.bashrc
.gem
.gitconfig
.inputrc
.minttyrc
.profile
buffers
char_enc_test
cybozu_1
escape_test_msys2.exe
FFC▒Ńo▒b▒N▒A▒b▒v▒▒▒Ă݂▒+Vor103.bat
opencv_test.cpp
[Inferior 1 (process 8200) exited normally]
(gdb) quit
```

Why do you think this is a bug in the MSYS2 path conversion code?

**Comment by DavidEGrayson** [comment]
I was able to reproduce your results with Visual Studio 2015 and I am a bit surprised.  It looks like MSYS2 does not expand a `*` argument when it is calling programs compiled by Visual Studio.  It does convert other paths, like `/c`, into the native Windows paths.

However, my theory is that MSYS2 does seems expand an argument of `*` whenever it is calling a MinGW program.  I posted [an interactive shell session](https://gist.github.com/DavidEGrayson/ce75f97c9d9f68b74e20ee849a154e15) that shows examples of that in an earlier post.  Your shell session is consistent with that, because `gdb` is most likely `/mingw64/bin/gdb.exe`, so it is a MinGW program, and MSYS2 would expand the `*` before it runs GDB, and GDB would never see the `*`.

**Comment by DavidEGrayson** [comment]
Yep, a lot of what I said in the post was wrong.  I now believe that some part of the MinGW startup code is expanding those arguments before calling main.  I added `while(1);` to my echoargs program so that it would last forever, and compiled it as a MinGW program.  Then I ran it from mingw64_shell.bat by typing

    ./mingw-echoargs.exe /c \*

When I look at the running process in Process Explorer, it shows the command line as:

    C:\path\to\mingw-echoargs.exe C:/ *

So, as far as the kernel is concerned, that process *was* started with a `*` as the argument.  However, the values in `argv` are different, and show that the `*` was expanded.

So this is not just a problem with MinGW GDB, it is a problem with every MinGW program.

**Comment by DavidEGrayson** [comment]
Yep.   If you clone git://git.code.sf.net/p/mingw-w64/mingw-w64 and look at `mingw-w64-crt/crt/wildcard.c` , you can see that MinGW globbing of wildcards.  It is disabled by default, but MSYS2 [enables it](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-crt-git/PKGBUILD) by passing the `--enable-wildcard` option when configuring the mingw-w64 crt.

You could disable it in any individual MinGW program by adding this line to it:

    int _dowildcard = 0;

**Comment by DavidEGrayson** [comment]
If you want to use gdb to see what a program does when an asterisk is passed to it, you can do it like this: start gdb by running `gdb myprogram`, and then when you are inside gdb, run the program by typing `run *`.  Whatever you type after `run` will be passed as arguments to the program being debugged.

**Comment by yumetodo** [comment]
![default](https://cloud.githubusercontent.com/assets/10869046/15266732/acdefae8-19e9-11e6-8a24-bd6d98f04720.png)

....?

**Comment by DavidEGrayson** [comment]
> myprogram: No such file or directory.

Do you have an executable in the current directory that is named `myprogram` or `myprogram.exe`?  You're supposed to put the name of your executable as the first argument to gdb.

**Comment by mati865** [comment]
@yumetodo best way to use gdb:
```
MINGW64 ~
$ gdb echo
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from echo...(no debugging symbols found)...done.
(gdb) run \*
Starting program: D:\msys64\usr\bin\echo.exe \*
[New Thread 4584.0x1458]
[New Thread 4584.0x160c]
[New Thread 4584.0xd38]
warning: cYgFFFFFFFF 18022A630 0
[New Thread 4584.0x1454]
warning: cYgstd 0xffffcb80 d 3
*
[Thread 4584.0xd38 exited with code 0]
[Thread 4584.0x160c exited with code 0]
[Thread 4584.0x1454 exited with code 0]
[Inferior 1 (process 4584) exited normally]
```

**Comment by yumetodo** [comment]
@mati865 thank you. same behavior.
