### ISSUE TITLE
qemu doesn't find dlls

### ISSUE THREAD

**Issue by Bobo1239** [Alexpux/MINGW-packages#1407]
After installing `mingw-w64-x86_64-qemu` and trying to run `qemu-system-x86_64` I receive the following error message:

```
C:/msys64/mingw64/bin/qemu-system-x86_64.exe: error while loading shared libraries: zlib1.dll: cannot open shared object file: No such file or directory
```

despite having a `zlib1.dll` in `C:\msys64\mingw64\bin`. I tried to circumvent the issue by copying the dlls (`zlib1.dll`, `libssh2-1.dll`, ...) to `C:\msys64\usr\bin`. But eventually I reached:

```
C:/msys64/mingw64/bin/qemu-system-x86_64.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by mati865** [comment]
> despite having a zlib1.dll in C:\msys64\mingw64\bin. I tried to circumvent the issue by copying the dlls (zlib1.dll, libssh2-1.dll, ...) to C:\msys64\usr\bin.

Don't do that or you can break your MSYS2 installation. I see that `mingw-w64-x86_64-zlib` dependency is missing and have to be installed manually but your workaround suggests you used wrong shell.
If you want to use `mingw-w64-*` packages you have to start them either in `mingw32` or `mingw64` shells.

**Comment by Bobo1239** [comment]
> Don't do that or you can break your MSYS2 installation.

I just did that to test things out (used a new MSYS2 installation).

I'm using the `mingw64` shell. (The `msys` shell doesn't even have qemu in it's `PATH`) I also tried reinstalling `mingw-w64-x86_64-zlib`. No success.
```
$ uname
MINGW64_NT-10.0

$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/Bobo1239/bin/:/home/Bobo1239/.cargo/bin
```

**Comment by mati865** [comment]
There must be something more missing. In my MSYS2 (also Win 10) `qemu-system-x86_64` doesn't crash. It just exits after few seconds.

**Comment by Bobo1239** [comment]
So I just tried it on a VM (Win 8; nothing besides Windows updates) with a fresh MSYS2 installation. The problem occurs regardless of updating MSYS2 or not before trying.

**Comment by Bobo1239** [comment]
Coincidentally, I think I just confirmed that `C:\msys64\mingw64\bin` is indeed in the DLL search path. I was using [diesel_cli](https://github.com/diesel-rs/diesel/tree/master/diesel_cli) and it complained that `libsqlite3-0.dll` could not be found. After installing `mingw-w64-x86_64-sqlite3` it worked flawlessly. 
Unfortunately no such luck with qemu.

**Comment by mati865** [comment]
I just experienced similar issue when trying to port OpenShot for MSYS. `openshot-audio-test-sound` doesn't find SEH library located in `/mingw64/bin`.

After changing working directory to `/mingw64/bin` it finds SEH lib but complain about OpenShot lib from `/mingw64/bin`.

**Comment by dmo2118** [comment]
I got this too. [Dependency Walker](http://www.dependencywalker.com/) said that I'm missing libnettle-6-1.dll and SDL.dll.

(Protip: If you're unfamiliar with Dependency Walker, use the x64 version with 64-bit EXEs, and the x86 version with 32-bit EXEs, because it gets confused otherwise.)

Pacman gave me libnettle-6-2.dll when it installed, so I just copied the new name to the old name.

The MSYS package depends on SDL2 (i.e. SDL2.dll), but QEMU is using SDL 1.2. I manually installed `mingw-w64-x86_64-SDL`, but I guess this needs to happen in [MINGW-packages](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qemu/PKGBUILD):

	--- a/mingw-w64-qemu/PKGBUILD	2016-06-25 23:46:40.584004400 -0400
	+++ b/mingw-w64-qemu/PKGBUILD	2016-06-25 23:47:03.283302800 -0400
	@@ -23,7 +23,7 @@
	          "${MINGW_PACKAGE_PREFIX}-lzo2"
	          "${MINGW_PACKAGE_PREFIX}-pixman"
	          "${MINGW_PACKAGE_PREFIX}-snappy"
	-         "${MINGW_PACKAGE_PREFIX}-SDL2")
	+         "${MINGW_PACKAGE_PREFIX}-SDL")
	 source=(http://wiki.qemu.org/download/${_realname}-${pkgver}.tar.bz2
	         001-time-functions.patch)
	 sha256sums=('72b0b991bbcc540663a019e1e8c4f714053b691dda32c9b9ee80b25f367e6620'


For the record: The directory from which the application loaded is automatically part of the DLL search path [[1]](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx#standard_search_order_for_desktop_applications); that's why DLLs live in the `bin` directory instead of the `lib` directory: it's automatic that way.

So yeah: `zlib1.dll: cannot open shared object file: No such file or directory` is a filthy filthy lie.

(Which is not to say that I actually have it working on my end...)

**Comment by dmo2118** [comment]
> There must be something more missing. In my MSYS2 (also Win 10) `qemu-system-x86_64` doesn't crash. It just exits after few seconds.

Don't forget: QEMU is an SDL app, so look for stdout.txt and stderr.txt in your current directory after you run it.

Also, it might be worth trying to attach a debugger to the process; see if there are any exceptions happening that Windows isn't telling you about. (For instance, [0xC0000028 STATUS_BAD_STACK](https://msdn.microsoft.com/en-us/library/cc704588.aspx))

**Comment by dmo2118** [comment]
Also, stderr.txt and stdout.txt may end up in `/mingw32/bin` or `/mingw64/bin` (wherever the QEMU executables are) instead of in your current directory.

And you'll probably need to do `qemu-system-x86_64 -L "C:\msys64\mingw64\etc\qemu"` in case you haven't figured that out already.

**Comment by Bobo1239** [comment]
I just found out that installing `mingw-w64-x86_64-usbredir` fixes qemu on my setup. The [Arch package](https://www.archlinux.org/packages/extra/x86_64/qemu/) also depends on `usbredir`.
Can somebody else confirm?

**Comment by dmo2118** [comment]
Just upgraded to QEMU 2.8, can confirm on my end.
