### ISSUE TITLE
mingw-w64-Win7AppId source is gone

### ISSUE THREAD

**Issue by elieux** [Alexpux/MINGW-packages#1460]
Source for the `mingw-w64-win7appid` package is gone from Google Code. Ideally, we should contact the author (David "didroe" Roe) and ask for a re-upload. As a backup plan, we can either use https://github.com/DavidEGrayson/win7appid, or upload the source to the @msys2 org ourselves.

**Comment by DavidEGrayson** [comment]
Do we have a way to contact didroe?  I couldn't see any contact information on the Google Code page.

**Comment by DavidEGrayson** [comment]
Actually, the source code is still there on Google Code, but it looks like it moved.  Starting at the project page ( https://code.google.com/archive/p/win7appid/ ), I was able to navigate to a ZIP file that contains the SVN repo:

https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/win7appid/source-archive.zip

Do we have a way to contact didroe?  I don't think the SVN repository contains his email address.

The win7appid proeject is very small and low-maintenance.  I would be happy maintain the win7appid project on my own GitHub account.  One of the first things I would do is add `LICENSE.txt` and the `win7appid.1`, so that we don't have to host those here in the MINGW-packages repo.

**Comment by galeksandrp** [comment]
#2313
