### ISSUE TITLE
imagemagick: mogrify does not recognize JPEGs

### ISSUE THREAD

**Issue by DavidEGrayson** [Alexpux/MINGW-packages#1609]
The mingw-w64-w86_64-imagemagick package (version 7.0.1.10-1) provides /mingw64/bin/mogrify.exe.  This utility can be used in Linux to re-encode a directory full of JPEG files, but it does not work in MSYS2 in the MinGW-w64 shell.  This shell session shows the command I ran in MSYS2 and the output from it:

```
$ mogrify -quality 90 20160801_18*jpg
mogrify.exe: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/508.
```

I'd suggest adding a test to the `check()` function of the PKGBUILD to ensure that this doesn't happen again.  But I don't know how to fix it.

See also #1534.

**Comment by whatsthepoint** [comment]
This is a path issue. The files are installed somewhere under /mingw64/lib/ImageMagick-7.0.1/, but ImageMagick can't find them for some reason. Similarly, if I try this:
```
$ convert -list configure

Path: [built-in]

Name           Value
-------------------------------------------------------------------------------
FEATURES       OpenMP
NAME           ImageMagick
QuantumDepth   16
convert.exe: unable to access configure file `configure.xml' @ warning/configure.c/GetConfigureOptions/710.

```
That doesn't work, but if I do this:
```
$ MAGICK_CONFIGURE_PATH=/mingw64/lib/ImageMagick-7.0.1/config-Q16HDRI convert -list configure
```
Then I get the expected output. I don't know why ImageMagick can't find its files either, because the output of configure _seems_ like the files are in the right places.

**Comment by peterbud** [comment]
@DavidEGrayson and @whatsthepoint : can you check the latest build #1905 ?
It supposed to solve this issue not finding delegates. If it works for you please close the issue.
