### ISSUE TITLE
gtk menu does not work when logged in with RDP

### ISSUE THREAD

**Issue by dave20** [Alexpux/MINGW-packages#2104]
Below is an example program, works fine unless you are logged in remotely via RDP:
```
#include <gtk/gtk.h>
int main(int argc,char **argv){
 GtkWidget *window,*box,*menu_bar,*menu_item,*menu,*menu_item2;
 GtkAccelGroup *accel_group;
 gtk_init(&argc,&argv);
 window=gtk_window_new(GTK_WINDOW_TOPLEVEL);
 g_signal_connect(window,"delete-event",G_CALLBACK(gtk_main_quit),NULL);
 box=gtk_box_new(GTK_ORIENTATION_VERTICAL,0);
 gtk_container_add(GTK_CONTAINER(window),box);
 menu_bar=gtk_menu_bar_new();
 gtk_box_pack_start(GTK_BOX(box),menu_bar,FALSE,FALSE,0);
 menu_item=gtk_menu_item_new_with_mnemonic("_File");
 gtk_menu_shell_append(GTK_MENU_SHELL(menu_bar),menu_item);
 menu=gtk_menu_new();
 gtk_menu_item_set_submenu(GTK_MENU_ITEM(menu_item),menu);
 menu_item2=gtk_menu_item_new_with_mnemonic("_Quit");
 gtk_menu_shell_append(GTK_MENU_SHELL(menu),menu_item2);
 g_signal_connect(menu_item2,"activate",G_CALLBACK(gtk_main_quit),NULL);
 accel_group=gtk_accel_group_new();
 gtk_window_add_accel_group(GTK_WINDOW(window),accel_group);
 gtk_widget_add_accelerator(menu_item2,"activate",accel_group,GDK_KEY_q,
  GDK_CONTROL_MASK,GTK_ACCEL_VISIBLE);
 gtk_widget_show_all(window);
 gtk_main();
 return 0;
}
```
compile command:
```
$ gcc test.c -o test `pkg-config.exe --cflags --libs gtk+-3.0`
 ```
run and click on the File menu nothing happens, following printed out in mintty:
```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

**Comment by achadwick** [comment]
This looks like an upstream error. It should probably have been filed against the GNOME bugtracker's [gtk+ "product"](https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B), under "Backend: Win32". Let's do some initial investigation while we're here though.

Have you tried to get a backtrace using gdb and your own debugging build of mingw-w64-gtk3-git yet? The upstream folks will definitely need that. Read the [HOWTO on the MyPaint wiki](https://github.com/mypaint/mypaint/wiki/Debugging-crashes-on-Windows) and adapt it for your needs if you are new to this.

The error message is a low level pixman assertion that [seems to come up a lot](https://bugzilla.gnome.org/buglist.cgi?bug_status=__all__&content=_pixman_log_error&no_redirect=1&order=bug_id%20DESC&product=gtk%2B&query_based_on=&query_format=specific) (and gets fixed). That's pretty reassuring.

**Comment by achadwick** [comment]
@dave20
Upstream bug report: https://bugzilla.gnome.org/show_bug.cgi?id=777527

**Comment by dave20** [comment]
Still does not work for me. Using Windows 7 professional, up to date. Not a huge issue, but annoying on occasion. Haven't attempted to debug it, only posted here. Sorry if it is the wrong place. Gnome bugzilla shows this as resolved and fixed, hmm.
mingw64 mingw-w64-x86_64-gtk3 3.22.24-1 [installed]

**Comment by achadwick** [comment]
@dave20 
Please approach the upstream maintainers via the GTK/GNOME Bugzilla and [report this](https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B) as a regression against the "Backend: Win32". Don't forget to point the upstream project at their earlier bugs . You may be the only person able to actively chase this (I don't have an RDP setup...)

Upstream will need a backtrace. I can't even tell you what you're seeing without a backtrace. Here are some HOWTOs I wrote a while back for a different project that covers some MSYS2 stuff:

* https://github.com/mypaint/mypaint/wiki/Debugging-crashes-on-Windows
* https://github.com/mypaint/mypaint/wiki/Building-GTK3-from-git-on-Windows

Please spend some time on this if you can, make those debugging builds, and get the backtrace. This bug cannot be fixed or even investigated without that backtrace.

When you report the regression upstream, please drop a link here so that other MSYS2 users who encounter it can get up to speed faster.

**Comment by lazka** [comment]
Looks related: https://bugzilla.gnome.org/show_bug.cgi?id=780101

**Comment by lazka** [comment]
As achadwick said, best to talk to upstream for this, not much we can do here to help.
