### ISSUE TITLE
msys2/mingw64 build shared library names

### ISSUE THREAD

**Issue by ScreamingInDigital** [Alexpux/MINGW-packages#2145]
This is not a "bug" with anything, but I would like to know why some shared libraries have a hyphen and a digit or multiple digits appended to a shared library name when they are created.

For some libraries like "readline", the shared library has the major version number appended to the end of the filename.   Other libraries such as "pcre" and "gmp" have a hyphen followed by a digit that does not correspond to the major version number.

For those that have options to build without autotools, such as using "cmake" to create a plain MinGW Makefile, the generated library and import library do not have these appended digits.

**Comment by Alexpux** [comment]
This is how developers decide to name libraries. See ````Makefile.{am,in}```` and find ````-version-info```` flags

**Comment by ScreamingInDigital** [comment]
Okay.  I will examine the automake file.

It still does not make any sense on some of these libraries,   The hyphen and digits appended to the end on several of them do not correspond to the major version number on several examples that I have seen.

**Comment by peterbud** [comment]
That is a very valid question. Sometimes I see extremes, when even the revision number is included in the file name like `libgettextlib-0-19-8-1.dll`. That means every time a new _revision_ comes out we need to recompile the whole dependent package or software, which IMHO would not be necessary as binary interface has not changed.

Don't we have a guideline which naming pattern should be used or makes sense?

**Comment by ScreamingInDigital** [comment]
I agree with peterbud.  Common sense would make you think to just append the major version number and maybe the minor version, but some of the small patches that get introduced, you end up with crazy names such as the above post.

And, as I mentioned before, I have found several examples where the appended numbers did not correspond to the version of the library.

**Comment by Alexpux** [comment]
@ScreamingInDigital, about library numbering you need ask developers of this library. This is not numbering by me.

**Comment by peterbud** [comment]
@ScreamingInDigital : can we make a list of packages where numbering seems to be odd? Then we can work on that list one-by-one.

**Comment by Alexpux** [comment]
@peterbud from what I remember:
- gnutls
- poppler
- hunspell
- imagemagick

But need to understand that for some reason you need rebuild set of packages when you update one of library because developers broke ABI compatibility

**Comment by mati865** [comment]
@peterbud, not entirely accurate and could be improved a bit but here is simple grep command https://gist.github.com/mati865/145b49c88fb253b0fb7cbb67b3e8790a

**Comment by peterbud** [comment]
@Alexpux 
> But need to understand that for some reason you need rebuild set of packages when you update one of library because developers broke ABI compatibility

The problem is that you need to recompile your dependent package even if the ABI has not changed, only a new reversion has been released.

Let's assume you have a software which uses `libgettextlib`. You compile your code, and distribute together with the shared library of `libgettextlib-0-19-8-1.dll`. If a new revision comes out from the shared `gettextlib` library, let say `libgettextlib-0-19-8-2.dll`, and you want to use it, it is not enough just to replace the shared library dll, but you need to recompile your own software, as your previously compiled software is still looking for a libray named `libgettextlib-0-19-8-1.dll`

Does this explain my concern?

**Comment by Alexpux** [comment]
I know it very good. See how many packages I'm rebuild last days.

**Comment by mingwandroid** [comment]
The numbers are part of 'semantic versioning'. There is no reason for us to second-guess the developer and remove them. You'll just end up with a lot of unresolved symbols instead of failure to load DLLs. I'd rather see that the DLL is missing than ending up questioning whether I'd used the right compilation flags in the dependent or not.

Linux uses symbolic links so that patch numbers do not prevent shared libraries from being found i.e. the SONAME tends to be e.g. libmpg.so.1 or libmpg.so.1.1 and those are symlinks to the ABI-compatible real file, which could vary from libmpg.so.1.1.0 ... libmpg.so.1.1.9 (for example).

So I would say please do not spend time doing this. The problems are worse on Windows (DLL hell) and we should retain as much differentiation as possible in the filenames.

To illustrate this, try running qtcreator. It currently segfaults, why? because it's not been rebuilt and doesn't have specific enough library names because the Qt Project went with the de-facto Windows standard without much concern for whether it was a good standard or not. AFAICT this has its roots in DOS 8.3 naming and serves no useful purpose these days.

Personally, I would elect to make it so that our Qt DLLs all end in `.5.8.dll` instead.

Regarding symlinks, Windows 10 insider preview now allows users permissions to create them by default, so we can consider in the future using them to allow patch-level versions to be represented in the real filenames without causing DLL load failures.

**Comment by mingwandroid** [comment]
Finally, if I had $1 for every time I ran into incompatible versions of libz1.dll in peoples' C:\Windows\System32 folder breaking software I work on, I'd have at least $10.

**Comment by ScreamingInDigital** [comment]
@mingwandroid Regarding "libz1" shared library, "Ha!".  That is another that has various names.  I have seen various names of zlib.  I have TDM-MINGW64 separate install, and it is "libzlib.dll"(latest version).

The recent use of "semantic versioning" still does not explain some of the extreme variations.  As for the deveopers intention, I agree, we have no idea why they do this.  I am sure some of them probably do not pay much attention to that either.
Why is the shared library for pcre called "libpcre-1.dll", when the current major.minor version is 8.40?

Regarding Linux, the crazy numbering scheme does not not really matter as long as you know the version of a library you have is ABI compatible, and as long the library version, if different, is compatible with the version of the library you need.  I have situations where I have had to manually create a symlink to an existing library.

I had no idea that Windows 10 can create symlinks.  Thanks.  I have created directory junctions, but I have never created a symlink.

As for the request that all DLLs are named "<library name>.<major version>.<minor version>.dll", I agree!

**Comment by ScreamingInDigital** [comment]
@Alexpux I know that you don't have any control of the output filename of a shared library that is not your own.  I am sure it would be easier from a package management perspective to have a consistent naming scheme.

**Comment by ScreamingInDigital** [comment]
@peterbud I will look at some of the existing libraries in my msys2/mingw64 installation, along with others that I plan to install for library names that do not closely match the version number.  It may require posting on some of the forums for those libraries to get an answer.

**Comment by mingwandroid** [comment]
You really didn't read what I wrote did you? You cherry picked and removed the context from a tiny part because you thought it sorted your argument.

I will object to any PR that attempts to remove any version information from shared libraries. It is one of the only defenses against DLL hell.

Please read up on how Windows searches for DLLs and consider people who install software that prepends to PATH after having installed msys2, then find their msys2 software crashing because DLLs from other software get loaded.

**Comment by mingwandroid** [comment]
For pcre they have maintained a compatible ABI fairly well, and the developers have chosen to number the shared libraries using the an ABI compatibility numbering scheme as many other projects do.

This stuff is not random and it is checked. https://abi-laboratory.pro/tracker/timeline/pcre/

Please leave the 8.3 legacy Windows defacto standards in the past where they belong (for even Microsoft version their DLLs carefully bite, check the UCRT DLLs for a good example of careful versioning).

Failure to load find DLL is way better than failure to find symbols in a DLL and worse, subtle hard to track down crashes in *apparently* the correct DLL (because someone thought striping all those 'weird numbers' was a good idea).

This issue should be closed.

**Comment by mingwandroid** [comment]
For sure though if you do find projects that follow sematic versioning and seem to over-specify their DLL names point it out to the upstream project maybe in a PR, and if you are right then they will likely accept it.

**Comment by ScreamingInDigital** [comment]
@mingwandroid And, you have not read what I wrote.  My original question had to do with inconsistency in naming conventions with shared libraries.  Why do some use an soname only and others have a major and/or minor version name only?  Even stranger, some provide multiple build methods that result in different filenames for the library.

You wrote "Personally, I would elect to make it so that our Qt DLLs all end in .5.8.dll instead.", and I posted that I agree.

Now that Windows supports symlinks, which I did not know, and I just checked is available from Win 7 - Win 10, would it not be better to push for consistency?  The symlink should reference the actual library with the version information.

I never objected to versioning of the DLLs.  I object to a **lack of consistency in naming convention** among various libraries.

I am well aware of the issue of "DLL hell".  I have frequently had to edit my global path in Windows to remove unnecessary path entries.

However, if you would like to continue to indirectly respond that I am a moron for asking the question, do not read posts correctly, and believe it is a waste of time to suggest that consistency in library version names and symlinks would by beneficial, the issue should be closed.

**Comment by mingwandroid** [comment]
The upstreams have elected to either use the number to represent 1) evolutions of ABI family (as per pcre) others 2) are less disciplined and just take the easy route of appending the full version number others 3) like qt take an awkard middle ground and the worst of all are 4) those who don't bother with numbers because that's what done other people do on Windows.

As packagers we clearly cannot standardise. Let me detail what happens with each choice:

1) You'd need to be intimately familiar with the ABI evolution going forwards of every package in msys2.

2) Every change to a dependency would cascade into requiring Alexey to rebuild all dependents.

3) You'd end up with less well specified DLL versions and would have to patch a lot of the software.  Some software would crash instead of reporting DLLs as missing.

4) Complete regression to DLL hell issues, lots of software crashing.

And all 4 require a *huge* amount of software to be patched and those patches to be maintained, only to end up with something less good that users of e.g. Linux and homebrew would not be familiar with.

I like the ABI family approach personally but it needs to be done upstream. For any software that does do this for Linux and macOS but disables it for Windows should a discussion with upstream should happen around enabling it there too.

**Comment by ScreamingInDigital** [comment]
Regarding your first comment on the "upstreams", I agree with you that there is a messy variation of numbering schemes on libraries.  This is my biggest complaint.  Also, some of them provide multiple methods for building(configure, CMakeLists) or directly provide Makefiles for a specific compiler or project files(Codeblocks,Visual Studio).  The generated library name on the Windows side usually has no versioning information at all, but the configure script build will generate either the semantic or ABI information in the name.  It would save a lot of headache, if this was consistent.

You provided a link to the ABI compatibility for several projects.  That is very helpful, but why don't each of the library developers provide this in their documentation?  I am sure some of them do, but it does not seem to be commonplace or at least something   It seems like a simple request.

Regarding each of your numbered choices, I have a small fraction of the available libraries in my mingw64/msys2 build.  I found three libraries with a semantic version specified and five with a hybrid of [major version]-[abi compatible version] in the name.  I understand rebuilding all dependents would be a headache, but it seems just ignoring this is "kicking the can down the road".  I think peterbud's approach of making a list of each semantic versioned library, requesting that the library developer(s) use ABI versioning in the build, provide an ABI compatible version to semantic versions in their documentation, and working one by one makes sense.  I would not expect an overnight change.

Your state that your preference is the ABI family approach, and that seems to be the most popular method for msys2/mingw{32|64} builds.  If that is the accepted naming convention, then it would be nice if that was done for all libraries.

Why not follow the approach with Linux for most shared libraries?  The ABI compatible/shared object name is a symlink to the actual library with the semantic version in the name.

**Comment by mingwandroid** [comment]
The problem with asking for upstreams to follow the ABI family approach is that it requires a great deal of knowledge of what makes and what breaks an ABI and a great deal of care around release time. Many open source projects don't have that knowledge nor time. Also some things can change behind their backs.

Unfortunately symlinks are not possible on Windows without special permissions. This has changed very recently in the Windows Insider builds, but we can't require our users to run that or to grant permissions (this will not be possible in many locked down installations at companies). In our case, symlinks end up as copies (which isn't the end of the world, but it does lose the symlink advantage).

If you find a library that's better versioned on Linux than it is on Windows, then the small change to the build system to use the Linux naming logic would generally be fine (we always prefer Linux file layouts on MSYS2 and have, on some projects such as mingw-w64-python, gone to some lengths to adopt this, and I consider shared library naming a part of the file layout).

But apart from that and aside from getting very involved in upstreams to understand their ABI evolution and to propose PRs with them, I would not try to let the inconsistency aspect not bother you too much.

**Comment by ScreamingInDigital** [comment]
The primary developers of a project should know what breaks ABI compatibility.  They should publish this in documentation change logs.  If you are the primary person or small group involved in applying updates and testing them, he/she/they should know this.

I do not believe it is asking too much for the maintainers of projects to keep track of this, put it into the documentation, and, if the ABI compatibility is broken, increase the ABI version.  I see this as a minor request for those projects that use the libraries.

I will concede that symlinks in Windows would be a much bigger challenge, because of the Administrator requirements in work environments with no administrative rights.  Also, there may be reluctance with those that have administrative rights at work or on their own personal computers to run the shell with these rights.  As I have said before, I would be satisfied with a consistent ABI versioning scheme with the library builds.  One of the widely used libraries, gettext, was mentioned by peterbud as an example that is using semantic versioning.

The inconsistency does aggravate me, because it is one of the primary causes of the "DLL Hell Hole".  I may start by asking on the "bug" web board why the msys2/mingw build uses a detailed semantic version in the library name versus an ABI version.  On my Linux box, gettext also has the semantic version name with no symlink created with an ABI name to the associated actual shared library file.
