### ISSUE TITLE
ninja - Why not in MSYS2-packages?

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MINGW-packages#2213]
Maybe a stupid question, but why is ninja located in MINGW-packages instead of MSYS2-packages?
Is there any advantage of having two flavors of this package?

**Comment by mati865** [comment]
MSYS2 packages repo is meant to be minimal and contain only things that are helpful for MINGW packages development.
Since there is mingw version of ninja which is probably faster (no Cygwin overhead) there is no point adding msys version unless there are compatibility issues.

**Comment by Ede123** [comment]
Thanks, I got the impression all build tools were supposed to got into MSYS2 packages and only libraries needed to build native applications (i.e. code that actually ends up in the native application) were supposed to go into MINGW packages.

I don't complain about having even faster builds, though. 😉

**Comment by mingwandroid** [comment]
Build tools that require a POSIX subsystem (Autotools) or fork (make though mingw32-make has a jobserver that doesn't need fork) go into msys2 packages.

Build tools that are required by packages that go into msys2 packages also go into msys2 packages because generally you can't use a native build tool to build a msys2 package (e.g. mingw-w64-x86_64-cmake could not be used to build msys2/clang).
