### ISSUE TITLE
What's difference about mingw-builds gcc and MINGW-packages gcc ?

### ISSUE THREAD

**Issue by RageCooky** [Alexpux/MINGW-packages#2282]
I found mingw-builds and msys2 are maintained by same people.
Is mingw-builds gcc more stable ?
Just curious to know the difference ...

**Comment by pal1000** [comment]
The most notable difference is that Msys2 provides that UNIX feeling. It includes bash with unix path system, but it has an important issue, If you want to build Windows 32-bit binaries from linux code , I'd stay away from Msys2 and use Mingw-w64 standalone. See #2271 and #2089.

**Comment by RageCooky** [comment]
Thanks ! Currently I just focus on C / C++, and I decide to use mingw-w64, considering the toolchain of Msys2 is unstable . . .

**Comment by mingwandroid** [comment]
> considering the toolchain of Msys2 is unstable

In what way? The MSYS2 toolchains are probably the most battle-tested Windows toolchains that exist since all of MSYS2 is compiled using them.

**Comment by mati865** [comment]
@mingwandroid check #2271 and #2089. Those 2 issues are correlated and probably cause is the same.

@pal1000, @RageCooky in MSYS2 toolchains defence we have it working while other toolchains fail: https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/5794B4EA.70802%40gmail.com/#msg35239053

**Comment by mingwandroid** [comment]
I read both of those issues.

There is little that indicates they are 100% a problem with our compilers and are unfortunately not minimal testcases either.

**Comment by pal1000** [comment]
Mingw-w64 standalone has a limitation as well . Command-line 2048 characters limit with Scons. This is a historical Scons bug that not every developer wanted to work around.  Because of this Mesa3D could never be built with Mingw-w64 standalone. 
As for msys2, the problem appears to be in i686-w64-mingw32-toolchain. At the same time x86_64-w64-mingw32-toolchai does not find certain CRT stuff when attempt to build livtxc_dxtn for 32-bit using -m32 parameter.

**Comment by mati865** [comment]
@pal1000 x86_64-w64-mingw32-toolchain is built without multilib support so it can produce 64 bit code only.
