### ISSUE TITLE
inkscape cannot export png

### ISSUE THREAD

**Issue by wanglongqi** [Alexpux/MINGW-packages#2393]
Last version inkscape works well. The lastest version cannot export png correctly. The error is related to the path. 

![image](https://cloud.githubusercontent.com/assets/6874783/25043173/8f0d1850-2150-11e7-8d60-b8d8b317ab92.png)

Changing the path to `/c/temp/bitmap.png` also returns error

![image](https://cloud.githubusercontent.com/assets/6874783/25043250/1c7f8a92-2151-11e7-9138-c0524682fa09.png)

Changing the path to `C:/temp/bitmap.png` also returns error

![image](https://cloud.githubusercontent.com/assets/6874783/25043253/22f52b66-2151-11e7-8ddd-63bc09e62a94.png)

The official version works well for this location.

**Comment by mati865** [comment]
I doubt it's path issue but rather error with libraries.

**Comment by wanglongqi** [comment]
@mati865 The official version can export to the same location for the same file.

**Comment by mati865** [comment]
@Ede123 Do you know how can we debug it?

**Comment by wanglongqi** [comment]
@mati865 Another thing may be related. I have a plugin [here](https://github.com/wanglongqi/WriteTeX), which tries to call `pdfcrop`. It runs smoothly in the inkscape in this project, but has some path issue in the official release. It seems the official version and inkscape in this project has a bit difference in dealing with the path.

**Comment by Ede123** [comment]
Could look into it in few days, I'm on holiday right now...


Am 14. April 2017 5:31:31 nachm. schrieb Mateusz Mikuła 
<notifications@github.com>:

**Comment by Ede123** [comment]
The issue arises because of MSYS2's patched version of glib2, see [upstream bug](https://bugs.launchpad.net/inkscape/+bug/1685091) for details (I explained the details in [comment #4](https://bugs.launchpad.net/inkscape/+bug/1685091/comments/4)).

This obviously is an Inkscape issue as it uses invalid file access specifiers like `wbb` so it certainly can and should be fixed upstream. That being said I'm not sure how helpful [the patch in question](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-glib2/0001-Use-CreateFile-on-Win32-to-make-sure-g_unlink-always.patch) actually is and if it might not cause more problems than it solves, so it might make sense to re-evaluate that one, too.

**Comment by Ede123** [comment]
Fixes committed upstream:
http://bazaar.launchpad.net/~inkscape.dev/inkscape/0.92.x/revision/15416
http://bazaar.launchpad.net/~inkscape.dev/inkscape/trunk/revision/15630
