### ISSUE TITLE
what’s up with qt5-static

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#2830]
I would like to have a recent build of qt5-static in the repos. 
If webkit is the hold-up i would like to point out again that it was never part of qt5-static because static builds of webkit were not supported – and would therefore be no regression. 
I’m currently in the process of building it manually, but wanted to start the conversation right away.

**Comment by irakhlin** [comment]
I am able to build qt5-static by essentially copying over the qt5 package PKGBUILD file and modifying the correct values to have it set to the static build of things. This produces a seemingly working Qt5.9.1 static build that I have been able to use to build a few of my Qt5 apps statically using qmake and qtcreator. It may be a good idea to copy over the exact syntax of the QT5 PKGBUILD file to qt5-static so they match as it seems the qt5 one was updated while the static one was not.. I dont see why they should be different as I imagine the reason the PKGBUILD is so complex is because it was meant to support building both depending on the settings of the switches set.

**Comment by Optiligence** [comment]
I also synced the PKGBUILDs before building. I will test our program when it’s done.

**Comment by stahta01** [comment]
I was the one that updated the Qt5 package for static; but, the package maintainer had an issue building it as static. I am guessing a required package was not new enough and that is why it failed.

Tim S.

**Comment by Optiligence** [comment]
Did you built it as committed, with examples on? Because that gets unreasonably large.

**Comment by stahta01** [comment]
Most of the time I built it without examples; but, I built it with examples at least once.
But, I built it only as 64 bit or 32 bit; because my hard drive did not have enough space to build both at once with examples and docs. Tim S.

**Comment by irakhlin** [comment]
Not to side track the issue but have you guys been able to successfully build the qt5-static package with LTO enabled? I have tried everything I could think of at this point but still get linker failures due to ar/gcc-ar not loading the lto plugin..

**Comment by Optiligence** [comment]
It’s linking successfully for me, but the resulting executable crashes during startup.

**Comment by Optiligence** [comment]
@Alexpux thx for uploading!
