### ISSUE TITLE
Inkscape 0.92.1 + poppler 0.59

### ISSUE THREAD

**Issue by Alexpux** [Alexpux/MINGW-packages#2852]
Currentry inkscape 0.92.1 not building with latest poppler 0.59.0

**Comment by Ede123** [comment]
It's due to changes to the `Object` class and the related API in poppler 0.58.

It will need to be fixed upstream, too (I started looking into it already but it requires some work).

**Comment by Alexpux** [comment]
Yeah many projects are broken by this API changes

**Comment by Alexpux** [comment]
@Ede123 I'm also see new error about using overloaded ````abs````. As workaround I add next patch:
````--- inkscape-0.92.1/src/libavoid/connector.cpp.orig	2017-09-06 11:42:09.353060000 +0300
+++ inkscape-0.92.1/src/libavoid/connector.cpp	2017-09-06 11:42:40.064816600 +0300
@@ -885,7 +885,7 @@
             {
                 // Check for consecutive points on opposite 
                 // corners of two touching shapes.
-                COLA_ASSERT(abs(i->pathNext->id.objID - i->id.objID) != 2);
+                COLA_ASSERT(abs((int)(i->pathNext->id.objID - i->id.objID)) != 2);
             }
         }
     }
````

**Comment by Ede123** [comment]
I'm not seeing the `abs` issue in my builds, so it has to be a difference between autotools (which PKGBUILD still uses) and cmake builds (which I'm using).

FYI we switched to MSYS2 for our "official" releases now, so most build issues should be fixed in 0.92.2 already (except some relocation stuff). Also we set up CI using AppVeyor and MSYS2, so most build issues are detected early (like in this case with poppler)

**Comment by Ede123** [comment]
Compatibility fix for poppler >= 0.58 [committed upstream](https://gitlab.com/inkscape/inkscape/commit/9418824967eb4c53371ef8588243fed4cab496e0)

If no regressions are found I'll backport it for the 0.92.x branch.

**Comment by Alexpux** [comment]
@Ede123 cool!
Then create pull request with patch into our repo.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/2b88bbf29913802eccf40fd27a2d5d699943b7df
