### ISSUE TITLE
Splitting mingw-w64-qt5

### ISSUE THREAD

**Issue by holgern** [Alexpux/MINGW-packages#2873]
Is there a reason why mingw-w64-qt5 is not splitted into several modules?
The base pkg file is huge and needs a lot of disk space.

Why not splitting it up as in archlinux?
https://www.archlinux.org/groups/x86_64/qt5/

**Comment by mingwandroid** [comment]
Difficulty and wanting to keep shared and static builds sharing (as much as possible) the same recipe.

Also risk of breaking everything, qtbinpatcher trickiness etc etc.

HD space is relatively cheap anyway and in many cases applications need a significant subset of the libs anyway so I don't see much real advantage. As soon as you install a couple of them you probably need the whole lot.

Oh and for developers it's easier this way.

The split I *can* see a good argument for is to put the debug libs in a different package for they are what take up the bulk of the bytes here.

**Comment by stahta01** [comment]
I am thinking of trying to split qt5-static into packages qt5-static  and qt5-base-static.
This way the things that only needs qt5-base-static have a smaller download.
I have issues downloading the current qt5 packages because of poor internet connection.
Any feedback on this idea. Plan to use only the one PKGBUILD file for both packages.

Tim S.

**Comment by Alexpux** [comment]
I don't see the reason to split qt5-static because no one package depends on it. This package is pure developer
