### ISSUE TITLE
Python 3.2 EXT_SUFFIX wrong 

### ISSUE THREAD

**Issue by welitonfreitas** [Alexpux/MINGW-packages#2884]
On Makefile ext Suffix for shared library is "-cpython-36m.dll" and correct is ".cpython-36m.dll". 
some libraries break down after they are installed

In python3.2 installer from python.org ext Suffix is ".cp36-win32.pyd"

**Comment by Alexpux** [comment]
@welitonfreitas this is our own Python builds and them incompatible with official builds because of many changes. You can't simply mix our python with official one

**Comment by welitonfreitas** [comment]
I know @Alexpux , I showed the result of the official release only to show that the hyphen is in place of the point. in the official specification exemplifies the use of the point in place of the hyphen.

https://www.python.org/dev/peps/pep-3149/

**Comment by Alexpux** [comment]
We have different naming and all our python modules have the same naming.

**Comment by mingwandroid** [comment]
We delivered do not want our DLLs to follow official Python guidelines here because they cannot be mixed with official Python DLLs.

It would be nice if CPython wrote a pep about encouraging free and open source compilers on Windows but I can't see that happening until then we'll pick and choose the peps we follow.

**Comment by lazka** [comment]
Since the issue in pillow is fixed now I'm closing this.
