### ISSUE TITLE
qtcreator only shows disassembler view when debugging v2

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#2888]
Despite #2882 gdb seems to “work” in qtcreator but displays something similar to #615 again, but this time i can’t test it outside msys2 because gdb then just hangs.

**Comment by Alexpux** [comment]
Duplicate https://github.com/Alexpux/MINGW-packages/issues/2882

**Comment by Optiligence** [comment]
i don’t think so, since this also appear with gdb downgraded to 7.12.1-3

**Comment by Optiligence** [comment]
@Alexpux ^

**Comment by Optiligence** [comment]
seems to be working again. idk since when tho

**Comment by WilliamKappler** [comment]
I'm getting this problem with MSYS2 provided: Qt Creator 4.8.1 / G++ 8.3.0 / GDB 7.12.1 / Windows 7. Saw several suggested fixes/work-arounds online but none had any effect, or didn't apply because of the nature of my project.

Every time the debugger advances/stops, breakpoint or otherwise, it opens the disassembly. Instruction-wise is off. It knows where it is in the source because I can switch back to the file and it has the execution cursor in the correct place, it just keeps opening disassembly for some reason. Here's what I get if I switch back to the file, plus the stack trace:

![file_view_and_stack](https://user-images.githubusercontent.com/13572055/53709438-492e2e80-3e06-11e9-8bba-e015f3b971dd.PNG)

I'm using a project based on pointing Creator at a CMakeLists.txt, not one internally created by Creator. Perhaps that is related?

**Comment by WilliamKappler** [comment]
It looks like, at least in my case, this might have to do with the paths given to the debugger. Almost all the paths in Creator are Windows-style. But if I am debugging and double-click a breakpoint, it (usually) will give me a message saying:
_Could not open "\c\some\file\path" for reading. Either the file does not exist or you do not have the permissions to open it._

**Comment by Optiligence** [comment]
For me it works atm., with a CMake/Qt project, qtcreator started from either an (msys2) mingw-shell or the task bar.

**Comment by WilliamKappler** [comment]
Unfortunately, it doesn't work for me in either case. I also tried moving the project to a folder right under C:/, which didn't help, on the guess the file paths might be too long or something, but no change. Tried updating everything in msys2, no change.

I believe the only path issues in Creator are variants of this one, connected to debugging. I haven't seen anything else misbehave, even symbol following hasn't yet misbehaved. Maybe it has something to do with gdb? I'm open to suggestions; perhaps I'll try building and debugging Creator myself.
