### ISSUE TITLE
How can I get windows header for windows 10 development?

### ISSUE THREAD

**Issue by wuhanck** [Alexpux/MINGW-packages#3116]
How can I update the header files for windows 10 development?
For example, there is no defintion for IOCTL_STORAGE_PROTOCOL_COMMAND.
How can I do with such things?

**Comment by mati865** [comment]
You would have to add definitions to MinGW-w64 project.

**Comment by StarWolf3000** [comment]
The headers from MinGW-w64 do not include several new definitions from the Windows 10 SDK (like that one mentioned). [MSDN on IOCTL_STORAGE_PROTOCOL_COMMAND](https://msdn.microsoft.com/en-us/library/windows/hardware/dn932068(v=vs.85).aspx)

You would need to implement them by yourself, since it's not advised to use the unmodified Windows 10 SDK with a GCC-style compiler environment (it wouldn't work anyway ootb).

**Comment by wuhanck** [comment]
thanks, guys.
