### ISSUE TITLE
mono: using wrong paths

### ISSUE THREAD

**Issue by wirx6** [Alexpux/MINGW-packages#3245]
```
$ csc
Cannot open assembly 'C:/building/msys64/mingw64/lib/mono/4.5/csc.exe': No such file or directory.
```
contents of `/mingw64/bin/csc`:
```
#!/bin/sh
exec /mingw64/bin/mono --gc-params=nursery-size=64m $MONO_OPTIONS C:/building/msys64/mingw64/lib/mono/4.5/csc.exe "$@"
```

**Comment by peterbud** [comment]
This is similar to #1670, the PKGBUILD needs to be modified

**Comment by revelator** [comment]
i assume c:\building is used to avoid the long path issue of windows ? if so this might be easier.

open a command prompt as admin and do subst x: c:\building now modify your buildscripts so that instead of referencing c:\building to use x: instead.
instant reward is that this aliased drive has no restrictions on path length.
i found out this little gem while trying to build qt5-static on win 7 64 but it continually failed because the path was to long.

**Comment by peterbud** [comment]
The proper solution is to fix the PKGBUILD IMHO

**Comment by revelator** [comment]
Not ment in regards to this particular error but my comment might prove usefull for some packages like nodejs.
