### ISSUE TITLE
python 3.6 EXTENSION_SUFFIXES without ".dll"

### ISSUE THREAD

**Issue by welitonfreitas** [Alexpux/MINGW-packages#3291]
on ```from importlib.machinery import EXTENSION_SUFFIXES``` return ```['-cpython-36m.dll', '-abi3.dll', '.cp36.pyd', '.pyd']```
should not ```.dll``` be included?

**Comment by Alexpux** [comment]
No. This is done to not mix MSVC and MINGW python. MINGW builds are not officially supoported by Python community

**Comment by lazka** [comment]
The official CPython only has `['.cp36.pyd', '.pyd']` I think. And the .dll extensions are some variant of PEP 3149 for Windows extensions. So I don't see why that list should include ".dll".

If the pyinstaller developers think that there is a bug in the MinGW Python or something could be improved there feel free to report it here.

**Comment by SulivanKuettler** [comment]
Hello !
I try to make a portable executable with python 3.6 x64. I am trying with PyInstaller. It works for simple code but when I try to import numpy, I cannot launch the executable because module multiarray (depending of numpy.core) cannot be imported.
If I copy/past the numpy folder, it works ! But only with msys2 environnement (launched with mingw64).
My spec-file is this simple code
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['essai_appli.py'],
             pathex=['C:/Users/sulivan.kuttler/Documents/000chtitPython/SV_SETTING'],
             binaries=[('C:\msys64\mingw64\lib\python3.6\lib-dynload\\*.dll','./')],
             datas= [
(r'C:\msys64\mingw64\lib\python3.6\lib2to3\Grammar.txt',
'lib2to3'),
(r'C:\msys64\mingw64\lib\python3.6\lib2to3\PatternGrammar.txt',
'lib2to3'),
],
             hiddenimports=['numpy.*'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='essai_appli',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='essai_appli')
```

And the code for testing :

```
from numpy import arange,asarray,where,mean,ndarray,zeros,resize,sign,append,sqrt,diag,ones,linspace,abs,sin,cos,nan,set_printoptions

tab = arange(10)

print(tab)

print("hello")
```


I have these warnings :

> Could not find platform independent libraries <prefix>
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]

And unfortunately, as it is not completely portable, I have with wondows console this error :

> ModuleNotFound: No module script named 'pyiboot03_importers'

Is it possible to import all necessary module locally with an easy way ?

Thanks !
