### ISSUE TITLE
Argon2 is not appearing on the online repositories

### ISSUE THREAD

**Issue by droidmonkey** [Alexpux/MINGW-packages#3304]
Argon2 was successfully merged several weeks ago and has not shown up in the online repositories. When issuing ```pacman -Ss argon``` nothing comes up.

**Comment by Alexpux** [comment]
Be patient because I’m only one person who build and upload packages

**Comment by droidmonkey** [comment]
I see, I thought it was automated from the CI. My apologies.

**Comment by Alexpux** [comment]
@droidmonkey next time see how you pack package. Why I need to fix every user added package?
See https://github.com/Alexpux/MINGW-packages/commit/64d12dd844ade7786faad51ef21c39460f30b78f

**Comment by droidmonkey** [comment]
The documentation you have on the creating package wiki is sparse. I followed a previously approved and working package as a template. Also I tested my package on a fresh MSYS2 build and it worked.

To me, if you require additional steps and fixes you should document that or post a template that would reduce your workload. I will use your edits for future submissions.

**Comment by Alexpux** [comment]
There are cannot be any documentation here. You must build package yourself and verify that all files are installed in the right locations at least.
In your case dll was at lib folder instead bin, also dll import library was not installed.

**Comment by phoerious** [comment]
Seriously, dude. We really appreciate the work you're doing, but you can't yell at contributors about things that aren't documented anywhere. If you require a *.pc file, you need to put a note about it in the wiki. Also your prefixes are all non-standard (/mingw64 etc.), so if you want people to put files in the right place, some more documentation would be helpful and reduce workload and stress level for everyone involved.

**Comment by Alexpux** [comment]
@phoerious I'm told about basic things like executables/dll and link libraries, other files are depend on program itself.

**Comment by phoerious** [comment]
Well, putting DLLs into /prefix/bin may be your convention, but on any *nix-like system, they are under /prefix/lib (that is, the .so files are there, which are the ELF equivalent to .dll). So how are we supposed to know that you want them under bin when there is no documentation about it?

**Comment by Alexpux** [comment]
@phoerious this is Windows, not UNIX so I think it is well known that DLL and EXE are on BIN folder.

**Comment by phoerious** [comment]
Well, no. Msys2 is originally based on Cygwin which is a port of POSIX/Unix binaries to Windows. So no, it's not known. If you think, this is obvious, then why don't you install that stuff to Windows/system32? There is no bin folder on Windows, hence it's not "obvious" that you want to have libraries there.
And apparently, it doesn't just appear that way to us, but also to other people. Otherwise you wouldn't complain that everybody does this wrong. I don't know how you guys do it, but we design our documentation and FAQ around what people have problems with, not around what we as the developers of our own system deem "obvious".

**Comment by mingwandroid** [comment]
@phoerious, the thing is, the contributor of the recipe cannot have even tried to install and run the software and that is *surely* obvious to everyone? Feel free to submit a PR to improve our documentation though.

**Comment by Alexpux** [comment]
@phoerious  if you look at Cygwin - it place DLL and EXE into BIN, so you are wrong here.

**Comment by phoerious** [comment]
I did not say that Cygwin did it differently, I said that it is a port of the Unix toolchain and coming from that, it is NOT obvious.
@mingwandroid It's a library package, so there is nothing you can "run" (except that little command line utility which nobody needs and which seems to link against the static lib anyway).

But anyway, I think this is pointless here. IMHO your documentation is lacking, but if you don't see it that way, well, tough luck.

**Comment by droidmonkey** [comment]
For the record i did test my package and it worked great for linking and running purposes. All future packages i will be cognizant of the requirements outlined in this thread. Closing this issue.

**Comment by Throne3d** [comment]
If there's ambiguity over where to place the relevant files, due to differing conventions between UNIX and Windows, it seems sensible to outline those somewhere.

@Alexpux, you stated there *cannot be* any documentation here, but this seems like a clear way to improve. It seems clear that it's *not* obvious, from how – as you say – people keep making mistakes when submitting their own versions of packages. Does the documentation explain this already? If so, should it be made more prominent, so people have a better chance of adhering to it? If not, do you think you should add this to the documentation somewhere?

**Comment by mingwandroid** [comment]
Documentation can be improved for sure, PRs welcome. This is how Open Source works.

**Comment by mingwandroid** [comment]
It's a library package that makes a DLL, that DLL will not get found in PATH if it is in lib. Maybe slightly less obvious, but not much.

Anyway thanks for you contribution @droidmonkey!
