### ISSUE TITLE
osgEarth failed to build

### ISSUE THREAD

**Issue by rhornig** [Alexpux/MINGW-packages#3385]
The osgEarth 2.9 version failed to build on the build server.

https://tea-ci.org/Alexpux/MINGW-packages/4766

This means that the repository still provides only osgEarth 2.8-3 which is NOT compatible with OpenSceneGraph 3.5.9 (the current version of OpenSceneGraph)

**Comment by filnet** [comment]
tea-ci has not been updated in a long while because of some wine issue.
A such it is missing newer packages like osgQt which osgearth depends on now.

That won't prevent @Alexpux to provide osgearth 2.9 when he gets round to it.

I'll push a fix for osgearth dependencies as it a mess currently (missing OSG...) but that will not change the tea-ci situation.

**Comment by filnet** [comment]
Please close this issue.

**Comment by rhornig** [comment]
Thanks a lot. The main issue was that osgEarth was non working in the current repo.
