### ISSUE TITLE
Help answer the most noobie quest..

### ISSUE THREAD

**Issue by BudiKusasi** [Alexpux/MINGW-packages#3424]
Sorry for naive question, but I really need the clear understanding on it..
Why and what's the reason of the directory /usr/local/bin precedes /usr/bin and /bin in environment PATH.. Thanks much in advance.

**Comment by lazka** [comment]
I'd guess to mirror what unix systems do normally.

you can run `cygpath -m /usr/local/bin` to get the Windows path equivalent btw.

**Comment by emmenlau** [comment]
The order dictates which executable is selected. Since the user may install their own executables to /usr/local/bin, I think the logic is: if there is an executable in /usr/local/bin then it should be prefered over an executable with the same name that is in the system directories /usr/bin and /bin.
But of course this is just a default. You can change PATH as you like.

**Comment by lazka** [comment]
@BudiKusasi Do you have any more questions?
