### ISSUE TITLE
glib: Information about your changes

### ISSUE THREAD

**Issue by Jehan** [Alexpux/MINGW-packages#3894]
Hello!

We have some freeze of GIMP 32-bit on Windows 10, and this is apparently fixed by using your patch glib from `mingw-w64-i686-glib2-2.56.1-2-any.pkg.tar.xz`.
See: https://gitlab.gnome.org/GNOME/gimp/issues/1516

So that we are able to handle the issue, we are trying to understand what is the exact issue which people encountered. I can see you are applying a bunch of patches on glib, and comparing to upstream repository, I can see that some patches are indeed merged in, whereas others are not.

Do you have any idea what fixed the freeze which some people encountered? Is it in glib upstream (in which case, we just have to bump our glib version requirement)? If not, we should report it to glib so that they can include the patch.
Any help appreciated. Thanks. :-)

**Comment by lazka** [comment]
* 0028-inode_directory.patch: No idea, maybe.. but why 32 bit only
* 0004-glib-prefer-constructors-over-DllMain.patch: just a build fix for static builds
* 0017-glib-use-gnu-print-scanf.patch: mingw specific, fixed in master when using meson
* 0023-print-in-binary-more-for-testing.all.patch: just for tests, I've dropped this in the -git package already
* 0001-Use-CreateFile-on-Win32-to-make-sure-g_unlink-always.patch: maybe.. https://bugzilla.gnome.org/show_bug.cgi?id=674214 but why 32 bit only
* W32-gstdio-Dont-try-to-get-reparse-tag-uncondition.patch: this is the empty drive patch mentioned by Michael

Another possible difference is that we build glib with the posix thread backend and not the win32 one.

**Comment by lazka** [comment]
@Jehan is there some way to force a 32bit install on a 64 bit system with the official GIMP installer?

**Comment by Jehan** [comment]
@lazka Apparently we used to have (with `/32` switch on command line), but late installers don't have it anymore. There is a bug report to get it back: https://gitlab.gnome.org/GNOME/gimp/issues/1470

**Comment by lazka** [comment]
I've worked around it now by installing with 32 bit wine

**Comment by lazka** [comment]
See https://gitlab.gnome.org/GNOME/gimp/issues/1516#note_232371

I think we can close this here.

**Comment by Jehan** [comment]
Yes let's close this here.
I just asked a last question on our tracker:

> And you also experienced the same issue with 32-bit GIMP on 64-bit Windows using the binaries provided by the default installer?

Just to make sure… :-)
