### ISSUE TITLE
mingw-w64-x86_64-z3  4.7.1-1 installs libz3.dll to lib instead of bin

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#3897]

**Comment by jputcu** [comment]
I think there is more going on, had troubles building my **rust** library which uses **clang**:

> Unable to find libclang: "the libclang shared library at C:\\msys64\\mingw64\\bin\\clang.dll could not be opened: The specified module could not be found. (os error 126)"

Running clang complained not finding the z3 library which is fixed by copying it to the bin folder, but now clang runs but without std output, e.g. from `clang --version` displayed nothing.
Downgrading the z3 fixed my issues. ` downgrading package mingw-w64-x86_64-z3 (4.7.1-1 => 4.6.0-1)`
