### ISSUE TITLE
libsrt refuses to compile under MinGW: missing C++11 headers for <thread>

### ISSUE THREAD

**Issue by LigH-de** [Alexpux/MINGW-packages#4355]
In https://github.com/jb-alvarado/media-autobuild_suite/issues/906 the configuration process for libsrt v1.3.0+ stops due to

```
-- C++ VERSION: Setting C++11 compat flag for gnu compiler
CMake Warning at CMakeLists.txt:629 (message):
  On MinGW, C++11 apps are blocked due to lacking proper C++11 headers for
  <thread>.  FIX IF POSSIBLE.
```

Do you see any way to add these to MSYS2, or do projects using libsrt (like ffmpeg) need to wait for a workaround?

**Comment by oscarfv** [comment]
Since one year or two ago, the C++ Standard Library that accompanies the GNU C++ compiler distributed by MSYS2 comes with a working <thread> header file. I use it on my cross-platform projects with no issues. Probably you are seeing an obsolete warning hard-coded on that project's CMake build script: it detects Mingw and assumes that C++11 thread support is still missing.

**Comment by oscarfv** [comment]
@LigH-de : since this issue is not caused by MinGW-packages, please close the bug report. Thanks.
