### ISSUE TITLE
Is there a mingw-w64 vim.

### ISSUE THREAD

**Issue by amosbird** [Alexpux/MINGW-packages#459]
The msys2 vim doesn't work with Youcompleteme. I also try to use a existing vim[https://bitbucket.org/Haroogan/vim-youcompleteme-for-windows], but it fails to response in terminal (it's like the interactive python problem). Then I try to build a vim using mingw-w64 toolchain. It's very frustrating. Is there a plan to supply a vim package here?

**Comment by mingwandroid** [comment]
No plans for this, no. You should investigate what goes wrong with Youcompleteme. Making new variants of packages because of one bug or incompatibility seems to me an extreme reaction.

If you think others would like a native Vim, then make a PKGBUILD and convince us that it's wanted, otherwise you can have packages in your own repository (and possibly share those with people).

**Comment by nak5124** [comment]
You need to compile Youcompleteme as msys2 application not native windows if you use it with msys2 vim.
Besides, don't mix win native apps with msys2 ones.
If you want to add vim into MINGW-packages, just cleate PR:)

**Comment by mingwandroid** [comment]
You can create a PR of course and we can discuss it but it adds to packaging overhead; we won't merge PRs unless they are potentially useful to many users.

**Comment by amosbird** [comment]
@nak5124 You're right. I mixed native apps with msys2 apps. How can I build Youcompleteme as msys2 while there are no msys2 gcc(and cmake, clang etc). I think I'm still missing something important.

**Comment by martell** [comment]
@amosbird "pacman -S gcc" That is the msys2 gcc.
You need to make a MSYS-Package
You use the makepkg and not makepkg-mingw script.

See here for other msys2 packages
https://github.com/Alexpux/MSYS2-packages
