### ISSUE TITLE
Difference between native python and mingw-w64 python.

### ISSUE THREAD

**Issue by amosbird** [Alexpux/MINGW-packages#470]
Is there any difference between the official released windows python and the mingw-w64 one?

**Comment by mingwandroid** [comment]
Yes a huge amount. MSYS2 only uses open source compilers - GCC to be specific. Python developers unfortunately do not share our viewpoint. Because of this we had to patch it *very* heavily:

https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-python3

The first half of the patches are by Roumen Petrov and the rest are by us.

You need to be more specific about what you are asking though. What difference are you worried about? They are incompatible, so do not yet to mix modules from one with the other.

**Comment by amosbird** [comment]
Ok, I'm mainly worried about performance difference.

**Comment by mingwandroid** [comment]
There will be performance differences in both directions. But then Python usually isn't about raw speed. Performance critical parts of your code should be done with something like cython instead, which we fully support, or else in C/C++.
