### ISSUE TITLE
Branching - Version Release?

### ISSUE THREAD

**Issue by pwmediaconsulting** [Alexpux/MINGW-packages#511]
For now on, this repository receives many contributions and updates, that's OK. But what about to have branching for "stable" set of packages.

I mean. For Gtk+, recently it was updated to 3.16.0 version, but may be it is very early for some others to use it in its software and they want to stay on 3.14.x (as me) adding any bug fixes release to it to get a rock solid version for a set of projects that could relay on this repository. Others would like to use the last version available, they can keep updated their local repositories with master.

Could we create branches for a set of packages, like gtk-3.14, where to push bug fixes releases?

The main problem here is how to manage this set of packages for other products out of Gtk. This could lead to maintain lot of branches.

For packages working "alone", with no dependencies on a set of other packages in this repository using just "compatible" versions, they could use TAGS.

This could lead to create a MINGW-packages release tarball, for stable use cases and build development environment in local repositories.

**Comment by mingwandroid** [comment]
We're a rolling release system because that's what we prefer. You don't have to update your system if you don't want to. Do you have a feeling for how much maintenance burden this would cause? Lots .. and lots.

You can lock packages with Pacman but this will make your system fail to upgrade or work correctly quite quickly: https://wiki.archlinux.org/index.php/pacman

Instead, you should solve this locally. Feel free to make your own repository from the upstream packages that are (what you consider) stable.
