### ISSUE TITLE
qt5: Qt5Gui CMake Config broken

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#539]
```
CMake Error at D:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:155 (macro_process_plugin_prl_file):
  Unknown CMake command "macro_process_plugin_prl_file".
Call Stack (most recent call first):
  D:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5Gui_QDDSPlugin.cmake:4 (_populate_Gui_plugin_properties)
  D:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:161 (include)
  D:/msys64/mingw64/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:97 (find_package)
  D:/msys64/mingw64/lib/cmake/Qt5/Qt5Config.cmake:26 (find_package)
  CMakeLists.txt:4 (find_package)
```

**Comment by mingwandroid** [comment]
Please give the reproduction steps.

**Comment by Optiligence** [comment]
```
project(qt5_test)
cmake_minimum_required(VERSION 3.0)

find_package(Qt5 REQUIRED COMPONENTS Core Widgets)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} Qt5::Core Qt5::Widgets)
```
`mkdir build && cd build && cmake -G Ninja .. && ninja`

**Comment by mingwandroid** [comment]
Thanks.

**Comment by mingwandroid** [comment]
@Optiligence: I fixed this in https://github.com/Alexpux/MINGW-packages/commit/767bc1dc19d89911413a39ae5a39a8e15a829f84

Alexey can't rebuild until the end of the week though, so if you need it now you'll need to rebuild, otherwise you can remove the lines that call macro_process_plugin_prl_file from each .cmake file as this is all that my change does (for non-static of course ..)

**Comment by Optiligence** [comment]
Thx, i use the previous package versions for now.

**Comment by Alexpux** [comment]
New build uploaded.

**Comment by Optiligence** [comment]
@Alexpux I would test it but both cmake packages currently don’t work because of the libarchive(nettle) update.
