### ISSUE TITLE
qtcreator only shows disassembler view when debugging

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#615]
Debugging works correctly with the official download from http://qt.io.

**Comment by Alexpux** [comment]
It works for me ok. Can you give more info?

**Comment by Optiligence** [comment]
```
project(hello)
cmake_minimum_required(VERSION 3.0)

add_executable(${PROJECT_NAME} main.cpp)
```
```
#include <iostream>

int main() {
	std::cout << "Hello World";
}
```
![image](https://cloud.githubusercontent.com/assets/1899299/7508249/8f371c4c-f47d-11e4-86ab-33c6226a7125.png)

**Comment by mingwandroid** [comment]
I've seen this and I tried to debug it but the problem went away! Also it only happened on one computer and not another. Is your msys2 not installed to C:? I wonder of that's related.

**Comment by Optiligence** [comment]
Yes, it is on `D:/`.

**Comment by Optiligence** [comment]
But on another PC i have it installed on `C:/` and it’s not working either.

**Comment by mingwandroid** [comment]
I actually suspect gcc or binutils more now. If you ask GDB to disassemble the code you'll see a lack of filenames, yet for components compiled with older tools I do see filenames.

**Comment by Optiligence** [comment]
But it works with the official qtcreator download, so…

**Comment by Optiligence** [comment]
Actually both work outside but don’t work when run from inside msys2 console.

**Comment by mingwandroid** [comment]
Weird. I thought I'd tracked down a likely fix in the upstream git repo, but no joy.

You are right though, I too always launch qt-creator from mingw64_shell.bat prompt (so that autotools and cmake have the correct env.) but if I use my pinned icon on the taskbar instead, the problem does not happen (but I can't run autotools).

This may explain why when I tried to debug this in Qt Creator (that gets confusing!) the problem didn't occur.

The only thing I really know for sure is that this bug is very annoying.

**Comment by elieux** [comment]
Report: we narrowed the difference to `MSYSTEM` being set to a non-empty string, regardless of the shell that was used to start Qt Creator.

**Comment by mingwandroid** [comment]
I've got a fix for this ready. I'll give more details when I get back in front of a computer.

**Comment by mingwandroid** [comment]
Actually here is the upstream merge request for now:

https://codereview.qt-project.org/#/c/112018/

**Comment by Optiligence** [comment]
Nice

**Comment by mingwandroid** [comment]
This should be fixed now.
