### ISSUE TITLE
Package request: LLD

### ISSUE THREAD

**Issue by ghost** [Alexpux/MINGW-packages#704]
As I tested, with great work of @martell and others, we can compile PE/COFF apps with clang-svn package from this repo now, but what's about linking? It still uses horribly slow `ld` from binutils, can we add a package for [LLD](https://github.com/llvm-mirror/lld) since [it supports PE/COFF for 64-bit](https://github.com/llvm-mirror/lld/tree/master/COFF#the-new-pecoff-linker) already?

**Comment by martell** [comment]
@procedural see 
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-clang-svn/0034-GNU-add-support-for-linking-PECOFF.patch

I am working on it. currently there is an issue between the difference between what dlltool and lib.exe produces. I'm currently having a discussion with LLD's main maintainer RUI on how to best tackle this atm :)

**Comment by procedural** [comment]
@martell good to know! Can you post progress here so I could test it when it'll be ready?

**Comment by martell** [comment]
Yes I'll message back here as soon as I have a patch for this issue. :)

**Comment by procedural** [comment]
@martell thank you again for this work... It already makes tremendous difference in terms of compile speed for my projects

**Comment by martell** [comment]
np glad it helps :)

3.7 will be tagged in a few days btw
We will upload packages for that once it is out :)

you can use the option -rtlib=compiler-rt now btw instead of using libgcc.

**Comment by martell** [comment]
also the thread for this discussion is here if you want to follow along :)
http://lists.cs.uiuc.edu/pipermail/llvmdev/2015-July/088556.html

**Comment by martell** [comment]
I have created a test case for this usage here.
http://reviews.llvm.org/D11724

Rui will implement it how he sees fit as he is the OWNER of the COFF linker :)
Chances are we won't provide this package under 3.7 in msys2 it will be svn only until 3.8 is released

Kind Regards
Martell

**Comment by procedural** [comment]
> Chances are we won't provide this package under 3.7 in msys2 it will be svn only until 3.8 is released

Better than nothing! :)

**Comment by martell** [comment]
@procedural Update:
We have made a package for this in 3.7.0
but keep in mind that lld only has support for x64 and arm on the 3.7.0 release... not x86

Ruiu from google was in the middle of creating a new COFF linker at the time so it was in a semi broken state falling back to the old PECOFF linker when it was branched

If you want to use lld as you linker you will have to rebuild the mingw-w64 crt with clang while using
https://github.com/martell/genlib instead of dlltool.
I'm hoping to get that merged back into the mingw-w64 project soon so we can have this by default.

@vpetrigo this might be interesting to you also as you are using clang also :)

Guys keep the bug reports coming here on github if you have any by the way.

I am traveling atm and will be back home towards the weekend then I can have a good look at all these issues / requests.

**Comment by JayFoxRox** [comment]
What's the current state of this? CC @Alexpux 

LLVM 4 was released; clang is already version 4 on this repo.
LLVM 4 officially included LLD now, so I'd expect this to be here too, but I couldn't find a folder for it?!

**Comment by mati865** [comment]
LLD is packaged for a long time but it cannot be used as ld replacement yet.

**Comment by JayFoxRox** [comment]
So this issue should be closed?
