### ISSUE TITLE
Install mingw-git using pacman

### ISSUE THREAD

**Issue by JoyceBabu** [Alexpux/MINGW-packages#832]
Is it possible to install mingw git from msys using pacman?

**Comment by mingwandroid** [comment]
It's not ready yet. You can use msys2 git in the meantime.

**Comment by JoyceBabu** [comment]
Thank you. I have already installed msys2 git, but it did not accept windows path. I guess I will have to stick with 'Git for windows' for now.

Is installing mingw packages from msys2 possible at all?

**Comment by Alexpux** [comment]
Of course you can install mingw packages from our repo

**Comment by JoyceBabu** [comment]
Thank you @Alexpux

**Comment by maoueh** [comment]
@JoyceBabu Git For Windows being based on MSYS2 (and being a native `mingw` program), it's possible to install this version inside MSYS2 directly (with some quirks, but rather small in my opinion). I have this exact setup and it works great for me.

Simply follow instructions https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper to install Git For Windows 2.x inside `MSYS2` directly.

Cheers.

**Comment by JoyceBabu** [comment]
@maoueh Thank you, that is simple and very useful. 

I have one more question. How can I make selected MSYS2 executables, available from CMD/PowerShell? Git for Windows currently allow you to add `git.exe` alone to `PATH`. Is it possible to create shims for selected executables from MSYS2?

**Comment by maoueh** [comment]
Usually, granularity is at the directory level meaning that all executables in a directory are exported by adding the said directory to `PATH`.

Usually, pure `MSYS2` executables are of little interest in PowerShell alone because they don't handle Windows path style correctly (but those not handling file paths can usually work). You probably more want to add `/mingw64/bin` to your `PATH`.

Simply add Windows path style of `/mingw64/bin` (obtained by using from MSYS2 shell the command `cygpath -w /mingw64/bin`) to Windows `PATH` environment variables. For example, I added `C:/Local/Msys2/mingw64/bin` to Windows `PATH` environment variable for example so `git` is available there. For some software however, they might need more than this but it's usually enough for most of them. Otherwise, that's more advanced stuff you will need to dig yourself.

Good luck,
Matt

**Comment by JoyceBabu** [comment]
Thank you Matt.

**Comment by ankostis** [comment]
But how can we locate the git installation instructions each time?
Google stopped serving  https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper among the first search results :-(

**Comment by Alexpux** [comment]
MSYS2 project not provide mingw version of GIT.
Look at git for Windows project
