### ISSUE TITLE
CMake autogenTargetName different from official

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MINGW-packages#923]
Is there a reason `autogenTargetName` is renamed from `_automoc` to `_autogen`? 
This i.e. makes it necessary to patch [cotire](https://github.com/sakra/cotire).

**Comment by mingwandroid** [comment]
This bug report is quite context free! Can you specify the package, and maybe isolate it down to the commit in which the change was made? I know it's Qt5-related, but in the spirit of providing good bug reports I'd like to see more effort expended :-)

**Comment by Optiligence** [comment]
https://github.com/Alexpux/MINGW-packages/commit/aa8f86ab267446002bcbb59e1455fbdf0d9f1cde#diff-4c9f45a9f09cd9ff5e35063610a2d954R29

**Comment by mingwandroid** [comment]
Well, since autostaticplugin came along we put more than automoc created files in that folder so that name is less appropriate than autogen. For cotire to care about that folder name seems a bit like it's reaching behind the scenes at an implementation detail somewhat?

Anyway, if you want to supply a patch that modifies qt5-static-plugin-support.patch to change it back then that's fine with me, I'll merge it.

**Comment by mingwandroid** [comment]
I'd like to see that patch necessary for cotire too if possible. Perhaps they can be convinced not to rely on implementation details?

**Comment by Optiligence** [comment]
I wouldn’t say that this is just an implementation detail: [_automoc target](https://cmake.org/cmake/help/v3.4/prop_tgt/AUTOMOC.html?highlight=_automoc), [_automoc file](https://cmake.org/cmake/help/v3.4/prop_tgt/AUTOGEN_TARGET_DEPENDS.html?highlight=_automoc). 

I agree that `autogen` fits the purpose more, idiomatically, not functionally (except it’s intended that users notice that this CMake works differently regarding this property). 
CMake already uses this for more than just the `moc` (`uic`, `rcc`), but i think they are keeping the name for backwards compatibility, especially regarding the links above. 

cotire usage: [file](https://github.com/sakra/cotire/blob/c55aeec38077a1ce099faa3628b5fab785ba5fb4/CMake/cotire.cmake#L2858:L2860), [target](https://github.com/sakra/cotire/blob/c55aeec38077a1ce099faa3628b5fab785ba5fb4/CMake/cotire.cmake#L2876:L2877)
I’m not sure if it’s possible to query the file and target in question differently.

**Comment by mingwandroid** [comment]
Would it be possible for you to try switching it back to _automoc and see if it works for AUTOSTATICPLUGINS mixed with AUTOMOC (and uic and rcc if possible too). They're handled a bit differently, being done at cmake execution time rather than build time ..

Otherwise we'll have to dig a bit deeper I think. My head's not in Qt5/CMake at present unfortunately. Many thanks for taking the time.

**Comment by Optiligence** [comment]
As none of the qt5 patches contain anything regarding `_autogen`, i assume this would work straight away. I will test a bit and then submit pull requests.

**Comment by Optiligence** [comment]
this is apparently a thing again

**Comment by Optiligence** [comment]
I’d like to open this again. @Alexpux @mingwandroid 
rationale is in the comment above: 
https://github.com/Alexpux/MINGW-packages/issues/923#issuecomment-162403630

**Comment by Optiligence** [comment]
fixed in 3.8.1 again 👍
