### ISSUE TITLE
gmp and mpfr can't pass test

### ISSUE THREAD

**Issue by silentmissile** [Alexpux/MINGW-packages#970]
for gmp-6.1.0 with patch, if I add --enable-cxx for configure, make check would fail when test the cxx module, all other tests passes. If I add --disable-cxx for configure, all tests passed in make check.

for mpfr-3.1.3 with patch, what ever parameters I add for configure, make check would fail, in 160 tests, only 11 can pass, 1 skip, and 148 fail

in your build script, I found make check, please confirm it

**Comment by elieux** [comment]
It's very much possible. We don't run tests regularly because often the tests themselves are broken on Windows and we don't have much time for that. If you know why the tests fail, we can work out a patch (either for upstream, or just for MSYS2) to fix that. Otherwise, use [`makepkg-mingw --nocheck`](https://www.archlinux.org/pacman/makepkg.8.html).
