### ISSUE TITLE
mingw-w64-pkg-config: check-cflags and check-sysroot failed (the compiler's sysroot isn't filtered from --cflags; maybe other flags too?)

### ISSUE THREAD

**Issue by wan-la** [Alexpux/MINGW-packages#982]
hi,

I have two checks failed when trying to install mingw-w64-pkg-config on my win7 machine. This seems to be a path issue. I run the check with both "msys2 shell" and "mingw-w64 win64 shell".

```
>make check
>make  check-TESTS
>make[1] : on entre dans le répertoire « /home/F072358/MINGW-packages-master/mingw-w64-pkg->config/src/build-x86_64-w64-mingw32/check »
>../pkg-config.exe --cflags simple :
>'-I/usr/include' != ''
>FAIL: check-cflags
>PASS: check-libs
>PASS: check-mixed-flags
>PASS: check-non-l-flags
>PASS: check-define-variable
>PASS: check-libs-private
>PASS: check-requires-private
>PASS: check-circular-requires
>PASS: check-includedir
>PASS: check-conflicts
>PASS: check-missing
>PASS: check-special-flags
>PASS: check-sort-order
>PASS: check-duplicate-flags
>PASS: check-whitespace
>PASS: check-cmd-options
>PASS: check-version
>PASS: check-requires-version
>PASS: check-print-options
>PASS: check-path
>../pkg-config.exe --cflags simple :
>'-IC:/msys64/sysroot/usr/include' != ''
>FAIL: check-sysroot
>PASS: check-uninstalled
>PASS: check-debug
>PASS: check-gtk
>PASS: check-tilde
>PASS: check-relocatable
>==============================================================================
>2 of 26 tests failed
>Please report to https://bugs.freedesktop.org/enter_bug.cgi?product=pkg-config
>==============================================================================
>Makefile:427 : la recette pour la cible « check-TESTS » a échouée
```

regards

**Comment by wan-la** [comment]
I just discovered pkgconf and it runs fine with it. The point is : is really pkg-config a good option for a development station using Mingw-64/MSYS2/MinGW-package ?

**Comment by hcorion** [comment]
I was able to build pkg-config manually, try that.

**Comment by mingwandroid** [comment]
@wan-la. This is a bug that needs to be fixed, many thanks for raising the issue. @Alexpux spent some time evaluating pkgconfig vs pkg-config and determined that in our opinions pkg-config is much better than pkgconfig. There is a term in England "don't throw the baby out with the bath-water" that is applicable here I think. I will change the title accordingly.

**Comment by wan-la** [comment]
Thanks all for pour responses. Well i am not sure i would  prefer pkg-config over pkgconf but i will be glad to use it when available. As i understand using one or another should be transparent, it is just a question of build (but maybe i missed some big points). Anyway my ultimate goal is to build gtk3 and i have a lot of others problems to solve.

**Comment by mingwandroid** [comment]
To build gtk3 you can use the following procedure:
```
cd ~/MINGW-packages/mingw-w64-gtk3
makepkg-mingw -sLf
```

**Comment by wan-la** [comment]
Sorry. I did not understand that prebuilt package where available for gtk3. This misjudgement had lead me to try to install this package from code not even using --syncdeps flag.

Everything is fine as i can run gtk3-demo. I could have save some CPU time using prebuilt package.

Well about pkgconf versus pkg-config.
Two days ago i only knew pkg-config. This utility was the only one i knew since it has replaced glib-config that -believe me or not- i have used. When i started to try to install gtk3 by hand from source i discovered that pkg-config was missing. Then i tried to install it also from source and i was stuck with make check failures. As i am at work, i must go fast, so the next point was "how to get pkg-config working ?" . I did not wanted to spend time on weird path consideration so i moved rapidly on pkgconf option. pkgconf has no check failure, this is why i prefer it and so do freebsd folks (http://www.mail-archive.com/freebsd-ports-announce@freebsd.org/msg00018.html).

Now if i have used prebuilt package of pkg-config i would steel prefer it not even knowing about pkgconf alternative.

Thanks a lot for your works, all of you, now i have a real alternative for my devs on Win7 and trust me i will use it!

**Comment by Alexpux** [comment]
In the past we try use pkgconf but we return to pkg-config because pkgconf not fully compatible with pkg-config.
Pkgconf don't convert paths from UNIX form to Windows. So some programs can't be correctly builded.

**Comment by wan-la** [comment]
pkgconf was said to behave like pkg-config and micmic all its features, bug included. Maybe it was in a unix/linux/*BSD environment. It could be useful to raises these issues to pkgconf team.

**Comment by mingwandroid** [comment]
These bugs are MSYS2 pkg-config bugs, not pkg-config bugs. We need to fix it in the short to medium term. There's no point at all in asking pkgconfig to emulate it in the meantime and then asking them to also remove their bug emulation later. That's just makework and hassle for them.

Don't worry, this bug is not very harmful, that fact has been proven 'in the field' over the course of the last year and a half or so of building countless MSYS2 packages. There are a number of cases where testsuites fail on MSYS2, usually due to the weird path conversion stuff that MSYS2 has to perform or else due to the fact that MSYS2 has a few different environments present instead of just one.

I am not for one minute saying this is not something that should be fixed. But fixing testsuite failures is less important than fixing actual bugs that cause programs to not compile or to misbehave.

**Comment by wan-la** [comment]
You are right.

About pkgconf i found https://github.com/pkgconf/pkgconf/issues/72.

**Comment by DavidEGrayson** [comment]
This was just a problem with the tests.  The tests assumed that /usr would be treated as a special directory and therefore /usr/include would be skipped in the clfags output.  I used sed to change /usr to `$MINGW_PREFIX` in that test.

Another test was expecting that `$(cd / && pwd -W)` would return a path without a trailing slash, but in fact it did.  (Isn't this kind of surprising?  pwd -W normally does not return a trailing slash, but it does for the root directory.)

**Comment by lazka** [comment]
Looks like this is fixed then..

**Comment by bit2shift** [comment]
`check-variable-override` and `check-system-flags` are currently failing on version 0.29.2.
```
(...)
PASS: check-relocatable
../pkg-config.exe --variable=prefix simple :
'/mingw64' != '/usr'
FAIL: check-variable-override
PASS: check-variables
PASS: check-dependencies
../pkg-config.exe --cflags system :
'-I/usr/include' != ''
FAIL: check-system-flags
==============================================================================
2 of 30 tests failed
Please report to https://bugs.freedesktop.org/enter_bug.cgi?product=pkg-config
==============================================================================
```
The first part of `check-variable-override` is trivial to fix, just need to replace `/usr` with `${MINGW_PREFIX}`.
But the part with `export PKG_CONFIG_SIMPLE_PREFIX="/foo"` is behaving as if `/foo` was being passed into `cygpath -w`, resulting in `C:/msys2/foo'` and causing that part of the test to fail.
<details>
<summary>Snippet of <code>make -C src/build-x86_64-w64-mingw32 check</code> running <code>check-variable-override</code></summary>
<pre>
../pkg-config.exe --variable=prefix simple :
'PKG_CONFIG_DEBUG_SPEW variable enabling debug spew
Adding directory '../../pkg-config-0.29.2/check' from PKG_CONFIG_PATH
Global variable definition 'pc_sysrootdir' = '/'
Global variable definition 'pc_top_builddir' = '$(top_builddir)'
Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Value of --silence-errors: 0
Error printing enabled
Adding virtual 'pkg-config' package to list of known packages
Looking for package 'simple'
Looking for package 'simple-uninstalled'
Reading 'simple' from file '../../pkg-config-0.29.2/check\simple.pc'
Parsing package file '../../pkg-config-0.29.2/check\simple.pc'
line>prefix=/mingw64
Variable declaration, 'prefix' has value '/mingw64'
line>exec_prefix=${prefix}
Overriding variable 'prefix' from environment
Variable declaration, 'exec_prefix' has value 'C:/msys2/foo'
line>libdir=${exec_prefix}/lib
Variable declaration, 'libdir' has value 'C:/msys2/foo/lib'
line>includedir=${prefix}/include
Overriding variable 'prefix' from environment
Variable declaration, 'includedir' has value 'C:/msys2/foo/include'
line>
line>Name: Simple test
line>Description: Dummy pkgconfig test package for testing pkgconfig
line>Version: 1.0.0
line>Requires:
line>Libs: -lsimple
line>Libs.private: -lm
Unknown keyword 'Libs.private' in '../../pkg-config-0.29.2/check\simple.pc'
line>Cflags: -I${includedir}
Path position of 'simple' is 1
Adding 'simple' to list of known packages
Overriding variable 'prefix' from environment
C:/msys2/foo' != '/foo'
FAIL: check-variable-override
</pre>
</details>
